"""Radar signal preprocessing C code generator.

Generates C source for a radar front-end pipeline:
  1. Range-Doppler FFT processing
  2. CFAR (Constant False Alarm Rate) detection
  3. Feature extraction feeding into a compiled Timber model
"""

from __future__ import annotations

import logging
import textwrap
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class RadarParams:
    """Radar waveform / hardware parameters."""

    n_chirps: int = 128
    n_samples: int = 256
    sample_rate_hz: float = 10e6
    carrier_freq_hz: float = 77e9
    bandwidth_hz: float = 4e9
    cfar_guard_cells: int = 4
    cfar_train_cells: int = 16
    cfar_threshold_db: float = 12.0
    max_detections: int = 64
    n_features: int = 6


class RadarCodeGenerator:
    """Emit C source that preprocesses raw radar ADC data for ML inference."""

    def __init__(self, params: RadarParams | None = None) -> None:
        self._p = params or RadarParams()

    # ------------------------------------------------------------------
    # Public
    # ------------------------------------------------------------------

    def generate(self, output_dir: str | Path) -> str:
        """Write radar_preprocess.h and radar_preprocess.c, return dir."""
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        (out / "radar_preprocess.h").write_text(self._header())
        (out / "radar_preprocess.c").write_text(self._source())
        logger.info("Radar preprocessing code generated at %s", out)
        return str(out)

    # ------------------------------------------------------------------
    # Header
    # ------------------------------------------------------------------

    def _header(self) -> str:
        p = self._p
        return textwrap.dedent(f"""\
            /* Auto-generated by TimberAccelerate — radar preprocessing */
            #ifndef RADAR_PREPROCESS_H
            #define RADAR_PREPROCESS_H

            #include <stdint.h>

            #define RADAR_N_CHIRPS       {p.n_chirps}
            #define RADAR_N_SAMPLES      {p.n_samples}
            #define RADAR_MAX_DETECTIONS {p.max_detections}
            #define RADAR_N_FEATURES     {p.n_features}

            typedef struct {{
                float range_m;
                float velocity_mps;
                float power_db;
                float snr_db;
                float azimuth_deg;
                float elevation_deg;
            }} RadarDetection;

            typedef struct {{
                int n_detections;
                RadarDetection detections[RADAR_MAX_DETECTIONS];
            }} RadarDetectionList;

            /* Full pipeline: raw ADC -> feature vector for ML model. */
            void radar_preprocess(const int16_t adc_data[RADAR_N_CHIRPS][RADAR_N_SAMPLES],
                                  float features_out[RADAR_MAX_DETECTIONS][RADAR_N_FEATURES],
                                  int* n_detections_out);

            /* Individual stages (exposed for unit testing). */
            void radar_range_doppler_fft(const int16_t adc[RADAR_N_CHIRPS][RADAR_N_SAMPLES],
                                         float magnitude[RADAR_N_CHIRPS][RADAR_N_SAMPLES]);

            void radar_cfar_detect(const float magnitude[RADAR_N_CHIRPS][RADAR_N_SAMPLES],
                                   RadarDetectionList* out);

            void radar_extract_features(const RadarDetectionList* dets,
                                        float features[RADAR_MAX_DETECTIONS][RADAR_N_FEATURES]);

            #endif /* RADAR_PREPROCESS_H */
        """)

    # ------------------------------------------------------------------
    # Source
    # ------------------------------------------------------------------

    def _source(self) -> str:
        p = self._p
        range_res = 3e8 / (2.0 * p.bandwidth_hz)
        vel_res = 3e8 / (2.0 * p.carrier_freq_hz * p.n_chirps * (1.0 / p.sample_rate_hz))
        return textwrap.dedent(f"""\
            /* Auto-generated by TimberAccelerate — radar preprocessing */
            #include "radar_preprocess.h"
            #include <math.h>
            #include <string.h>

            /* --- constants derived from radar parameters --- */
            static const float RANGE_RES_M    = {range_res:.6e}f;
            static const float VELOCITY_RES   = {vel_res:.6e}f;
            static const int   GUARD_CELLS    = {p.cfar_guard_cells};
            static const int   TRAIN_CELLS    = {p.cfar_train_cells};
            static const float CFAR_ALPHA     = {10 ** (p.cfar_threshold_db / 10.0):.4f}f;

            /* -------------------------------------------------- */
            /* Placeholder FFT — replace with optimised library    */
            /* (e.g. CMSIS-DSP, FFTW, or vendor-specific)         */
            /* -------------------------------------------------- */
            static void fft_1d_real(const float* in, float* mag, int n) {{
                /* Naive DFT magnitude — O(n^2), swap for real FFT. */
                for (int k = 0; k < n; k++) {{
                    float re = 0.0f, im = 0.0f;
                    for (int j = 0; j < n; j++) {{
                        float angle = -2.0f * (float)M_PI * k * j / n;
                        re += in[j] * cosf(angle);
                        im += in[j] * sinf(angle);
                    }}
                    mag[k] = sqrtf(re * re + im * im);
                }}
            }}

            void radar_range_doppler_fft(
                    const int16_t adc[RADAR_N_CHIRPS][RADAR_N_SAMPLES],
                    float magnitude[RADAR_N_CHIRPS][RADAR_N_SAMPLES]) {{
                float row_f[RADAR_N_SAMPLES];
                float col_f[RADAR_N_CHIRPS];
                float col_mag[RADAR_N_CHIRPS];
                float range_fft[RADAR_N_CHIRPS][RADAR_N_SAMPLES];

                /* Range FFT (per chirp) */
                for (int c = 0; c < RADAR_N_CHIRPS; c++) {{
                    for (int s = 0; s < RADAR_N_SAMPLES; s++)
                        row_f[s] = (float)adc[c][s];
                    fft_1d_real(row_f, range_fft[c], RADAR_N_SAMPLES);
                }}

                /* Doppler FFT (per range bin) */
                for (int s = 0; s < RADAR_N_SAMPLES; s++) {{
                    for (int c = 0; c < RADAR_N_CHIRPS; c++)
                        col_f[c] = range_fft[c][s];
                    fft_1d_real(col_f, col_mag, RADAR_N_CHIRPS);
                    for (int c = 0; c < RADAR_N_CHIRPS; c++)
                        magnitude[c][s] = col_mag[c];
                }}
            }}

            void radar_cfar_detect(
                    const float magnitude[RADAR_N_CHIRPS][RADAR_N_SAMPLES],
                    RadarDetectionList* out) {{
                out->n_detections = 0;
                int half = GUARD_CELLS + TRAIN_CELLS;

                for (int r = half; r < RADAR_N_CHIRPS - half; r++) {{
                    for (int d = half; d < RADAR_N_SAMPLES - half; d++) {{
                        float noise_sum = 0.0f;
                        int count = 0;
                        for (int i = -half; i <= half; i++) {{
                            if (i >= -GUARD_CELLS && i <= GUARD_CELLS) continue;
                            noise_sum += magnitude[r + i][d];
                            count++;
                        }}
                        if (count == 0) continue;
                        float avg = noise_sum / count;
                        float threshold = CFAR_ALPHA * avg;
                        if (magnitude[r][d] > threshold) {{
                            if (out->n_detections >= RADAR_MAX_DETECTIONS) return;
                            RadarDetection* det = &out->detections[out->n_detections];
                            det->range_m      = d * RANGE_RES_M;
                            det->velocity_mps = (r - RADAR_N_CHIRPS / 2) * VELOCITY_RES;
                            det->power_db     = 20.0f * log10f(magnitude[r][d] + 1e-12f);
                            float noise_floor = 20.0f * log10f(avg + 1e-12f);
                            det->snr_db       = det->power_db - noise_floor;
                            det->azimuth_deg  = 0.0f;   /* requires antenna array processing */
                            det->elevation_deg = 0.0f;
                            out->n_detections++;
                        }}
                    }}
                }}
            }}

            void radar_extract_features(
                    const RadarDetectionList* dets,
                    float features[RADAR_MAX_DETECTIONS][RADAR_N_FEATURES]) {{
                for (int i = 0; i < dets->n_detections; i++) {{
                    const RadarDetection* d = &dets->detections[i];
                    features[i][0] = d->range_m;
                    features[i][1] = d->velocity_mps;
                    features[i][2] = d->power_db;
                    features[i][3] = d->snr_db;
                    features[i][4] = d->azimuth_deg;
                    features[i][5] = d->elevation_deg;
                }}
            }}

            void radar_preprocess(
                    const int16_t adc_data[RADAR_N_CHIRPS][RADAR_N_SAMPLES],
                    float features_out[RADAR_MAX_DETECTIONS][RADAR_N_FEATURES],
                    int* n_detections_out) {{
                float magnitude[RADAR_N_CHIRPS][RADAR_N_SAMPLES];
                RadarDetectionList dets;

                radar_range_doppler_fft(adc_data, magnitude);
                radar_cfar_detect(magnitude, &dets);
                radar_extract_features(&dets, features_out);
                *n_detections_out = dets.n_detections;
            }}
        """)
