"""RF signal preprocessing C code generator.

Generates C source for an RF classification front-end:
  1. FFT of I/Q samples
  2. Power spectral density estimation
  3. Feature extraction for a compiled Timber classifier
"""

from __future__ import annotations

import logging
import textwrap
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class RFParams:
    """RF front-end parameters."""

    n_samples: int = 1024
    sample_rate_hz: float = 20e6
    fft_size: int = 1024
    n_psd_bins: int = 128
    n_features: int = 16
    center_freq_hz: float = 2.4e9


class RFCodeGenerator:
    """Emit C source that preprocesses raw I/Q data for ML signal classification."""

    def __init__(self, params: RFParams | None = None) -> None:
        self._p = params or RFParams()

    def generate(self, output_dir: str | Path) -> str:
        """Write rf_preprocess.h and rf_preprocess.c, return dir."""
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        (out / "rf_preprocess.h").write_text(self._header())
        (out / "rf_preprocess.c").write_text(self._source())
        logger.info("RF preprocessing code generated at %s", out)
        return str(out)

    def _header(self) -> str:
        p = self._p
        return textwrap.dedent(f"""\
            /* Auto-generated by TimberAccelerate — RF preprocessing */
            #ifndef RF_PREPROCESS_H
            #define RF_PREPROCESS_H

            #include <stdint.h>

            #define RF_N_SAMPLES   {p.n_samples}
            #define RF_FFT_SIZE    {p.fft_size}
            #define RF_N_PSD_BINS  {p.n_psd_bins}
            #define RF_N_FEATURES  {p.n_features}

            /* Full pipeline: raw I/Q -> feature vector for ML model. */
            void rf_preprocess(const float iq_i[RF_N_SAMPLES],
                               const float iq_q[RF_N_SAMPLES],
                               float features_out[RF_N_FEATURES]);

            /* Individual stages. */
            void rf_compute_fft_magnitude(const float i[RF_N_SAMPLES],
                                          const float q[RF_N_SAMPLES],
                                          float mag[RF_FFT_SIZE]);

            void rf_compute_psd(const float mag[RF_FFT_SIZE],
                                float psd[RF_N_PSD_BINS]);

            void rf_extract_features(const float psd[RF_N_PSD_BINS],
                                     const float mag[RF_FFT_SIZE],
                                     float features[RF_N_FEATURES]);

            #endif /* RF_PREPROCESS_H */
        """)

    def _source(self) -> str:
        p = self._p
        bin_width = p.sample_rate_hz / p.fft_size
        bins_per_psd = p.fft_size // p.n_psd_bins
        return textwrap.dedent(f"""\
            /* Auto-generated by TimberAccelerate — RF preprocessing */
            #include "rf_preprocess.h"
            #include <math.h>
            #include <string.h>

            static const float BIN_WIDTH_HZ     = {bin_width:.2f}f;
            static const int   BINS_PER_PSD_BIN = {bins_per_psd};

            /* Placeholder complex DFT magnitude — swap for optimised FFT. */
            void rf_compute_fft_magnitude(const float i_in[RF_N_SAMPLES],
                                          const float q_in[RF_N_SAMPLES],
                                          float mag[RF_FFT_SIZE]) {{
                for (int k = 0; k < RF_FFT_SIZE; k++) {{
                    float re = 0.0f, im = 0.0f;
                    for (int n = 0; n < RF_N_SAMPLES; n++) {{
                        float angle = -2.0f * (float)M_PI * k * n / RF_FFT_SIZE;
                        re += i_in[n] * cosf(angle) - q_in[n] * sinf(angle);
                        im += i_in[n] * sinf(angle) + q_in[n] * cosf(angle);
                    }}
                    mag[k] = sqrtf(re * re + im * im) / RF_FFT_SIZE;
                }}
            }}

            void rf_compute_psd(const float mag[RF_FFT_SIZE],
                                float psd[RF_N_PSD_BINS]) {{
                for (int b = 0; b < RF_N_PSD_BINS; b++) {{
                    float sum = 0.0f;
                    int start = b * BINS_PER_PSD_BIN;
                    for (int j = 0; j < BINS_PER_PSD_BIN; j++) {{
                        float m = mag[start + j];
                        sum += m * m;
                    }}
                    psd[b] = 10.0f * log10f(sum / BINS_PER_PSD_BIN + 1e-12f);
                }}
            }}

            void rf_extract_features(const float psd[RF_N_PSD_BINS],
                                     const float mag[RF_FFT_SIZE],
                                     float features[RF_N_FEATURES]) {{
                /* Feature 0: total power */
                float total_power = 0.0f;
                for (int i = 0; i < RF_FFT_SIZE; i++)
                    total_power += mag[i] * mag[i];
                features[0] = 10.0f * log10f(total_power + 1e-12f);

                /* Feature 1: peak frequency bin */
                float peak_val = 0.0f;
                int peak_idx = 0;
                for (int i = 0; i < RF_FFT_SIZE; i++) {{
                    if (mag[i] > peak_val) {{ peak_val = mag[i]; peak_idx = i; }}
                }}
                features[1] = (float)peak_idx * BIN_WIDTH_HZ;

                /* Feature 2: peak power */
                features[2] = 20.0f * log10f(peak_val + 1e-12f);

                /* Feature 3: spectral centroid */
                float weighted_sum = 0.0f, mag_sum = 0.0f;
                for (int i = 0; i < RF_FFT_SIZE; i++) {{
                    weighted_sum += i * mag[i];
                    mag_sum += mag[i];
                }}
                features[3] = (mag_sum > 1e-12f) ? weighted_sum / mag_sum : 0.0f;

                /* Feature 4: spectral spread */
                float centroid = features[3];
                float spread = 0.0f;
                for (int i = 0; i < RF_FFT_SIZE; i++) {{
                    float diff = (float)i - centroid;
                    spread += diff * diff * mag[i];
                }}
                features[4] = (mag_sum > 1e-12f) ? sqrtf(spread / mag_sum) : 0.0f;

                /* Feature 5: spectral flatness (geometric / arithmetic mean of PSD) */
                float log_sum = 0.0f, arith_sum = 0.0f;
                for (int b = 0; b < RF_N_PSD_BINS; b++) {{
                    float lin = powf(10.0f, psd[b] / 10.0f);
                    log_sum += logf(lin + 1e-12f);
                    arith_sum += lin;
                }}
                float geo_mean = expf(log_sum / RF_N_PSD_BINS);
                float ari_mean = arith_sum / RF_N_PSD_BINS;
                features[5] = (ari_mean > 1e-12f) ? geo_mean / ari_mean : 0.0f;

                /* Features 6-9: PSD quartile energies */
                int q_size = RF_N_PSD_BINS / 4;
                for (int q = 0; q < 4; q++) {{
                    float e = 0.0f;
                    for (int b = q * q_size; b < (q + 1) * q_size; b++)
                        e += powf(10.0f, psd[b] / 10.0f);
                    features[6 + q] = 10.0f * log10f(e + 1e-12f);
                }}

                /* Features 10-15: bandwidth metrics (3dB, 10dB, 20dB, kurtosis, skew, crest) */
                float peak_db = features[2];
                int bw3 = 0, bw10 = 0, bw20 = 0;
                for (int i = 0; i < RF_FFT_SIZE; i++) {{
                    float db = 20.0f * log10f(mag[i] + 1e-12f);
                    if (db >= peak_db - 3.0f)  bw3++;
                    if (db >= peak_db - 10.0f) bw10++;
                    if (db >= peak_db - 20.0f) bw20++;
                }}
                features[10] = (float)bw3  * BIN_WIDTH_HZ;
                features[11] = (float)bw10 * BIN_WIDTH_HZ;
                features[12] = (float)bw20 * BIN_WIDTH_HZ;

                /* Spectral kurtosis */
                float m2 = 0.0f, m4 = 0.0f;
                for (int i = 0; i < RF_FFT_SIZE; i++) {{
                    float diff = (float)i - centroid;
                    float d2 = diff * diff * mag[i];
                    m2 += d2;
                    m4 += d2 * diff * diff;
                }}
                features[13] = (m2 > 1e-12f) ? (m4 / mag_sum) / ((m2 / mag_sum) * (m2 / mag_sum)) : 0.0f;

                /* Spectral skewness */
                float m3 = 0.0f;
                for (int i = 0; i < RF_FFT_SIZE; i++) {{
                    float diff = (float)i - centroid;
                    m3 += diff * diff * diff * mag[i];
                }}
                float sigma = features[4];
                features[14] = (sigma > 1e-12f && mag_sum > 1e-12f)
                    ? (m3 / mag_sum) / (sigma * sigma * sigma) : 0.0f;

                /* Crest factor */
                float rms = sqrtf(total_power / RF_FFT_SIZE);
                features[15] = (rms > 1e-12f) ? peak_val / rms : 0.0f;
            }}

            void rf_preprocess(const float iq_i[RF_N_SAMPLES],
                               const float iq_q[RF_N_SAMPLES],
                               float features_out[RF_N_FEATURES]) {{
                float mag[RF_FFT_SIZE];
                float psd[RF_N_PSD_BINS];

                rf_compute_fft_magnitude(iq_i, iq_q, mag);
                rf_compute_psd(mag, psd);
                rf_extract_features(psd, mag, features_out);
            }}
        """)
