"""Telemetry data preprocessing C code generator.

Generates C source for a telemetry anomaly-detection front-end:
  1. Sliding-window feature extraction (mean, variance, min, max)
  2. Normalization against provided statistics
  3. Feature vector output for a compiled Timber anomaly model
"""

from __future__ import annotations

import logging
import textwrap
from dataclasses import dataclass, field
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class TelemetryParams:
    """Telemetry preprocessing configuration."""

    n_channels: int = 8
    window_size: int = 64
    stride: int = 16
    features_per_channel: int = 4  # mean, var, min, max
    normalize: bool = True
    channel_means: list[float] = field(default_factory=list)
    channel_stds: list[float] = field(default_factory=list)

    @property
    def n_features(self) -> int:
        return self.n_channels * self.features_per_channel


class TelemetryCodeGenerator:
    """Emit C source that preprocesses telemetry streams for ML inference."""

    def __init__(self, params: TelemetryParams | None = None) -> None:
        self._p = params or TelemetryParams()

    def generate(self, output_dir: str | Path) -> str:
        """Write telemetry_preprocess.h and .c, return dir."""
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        (out / "telemetry_preprocess.h").write_text(self._header())
        (out / "telemetry_preprocess.c").write_text(self._source())
        logger.info("Telemetry preprocessing code generated at %s", out)
        return str(out)

    def _header(self) -> str:
        p = self._p
        return textwrap.dedent(f"""\
            /* Auto-generated by TimberAccelerate — telemetry preprocessing */
            #ifndef TELEMETRY_PREPROCESS_H
            #define TELEMETRY_PREPROCESS_H

            #define TELEM_N_CHANNELS          {p.n_channels}
            #define TELEM_WINDOW_SIZE         {p.window_size}
            #define TELEM_STRIDE              {p.stride}
            #define TELEM_FEATURES_PER_CH     {p.features_per_channel}
            #define TELEM_N_FEATURES          {p.n_features}

            /* Sliding window state. */
            typedef struct {{
                float buffer[TELEM_N_CHANNELS][TELEM_WINDOW_SIZE];
                int   write_pos;
                int   samples_received;
            }} TelemetryWindow;

            /* Initialise the sliding window state. */
            void telem_window_init(TelemetryWindow* w);

            /* Push one multi-channel sample. Returns 1 when a full window is ready. */
            int telem_window_push(TelemetryWindow* w, const float sample[TELEM_N_CHANNELS]);

            /* Extract features from the current window into *features_out*. */
            void telem_extract_features(const TelemetryWindow* w,
                                        float features_out[TELEM_N_FEATURES]);

            /* Normalise a feature vector in-place using provided statistics. */
            void telem_normalize(float features[TELEM_N_FEATURES]);

            /* Full pipeline: push sample, extract & normalise when ready.
               Returns 1 and fills features_out when a window completes. */
            int telem_preprocess_sample(TelemetryWindow* w,
                                        const float sample[TELEM_N_CHANNELS],
                                        float features_out[TELEM_N_FEATURES]);

            #endif /* TELEMETRY_PREPROCESS_H */
        """)

    def _source(self) -> str:
        p = self._p

        # Build normalization arrays
        if p.normalize and p.channel_means and p.channel_stds:
            means_init = ", ".join(f"{m:.6f}f" for m in p.channel_means)
            stds_init = ", ".join(f"{s:.6f}f" for s in p.channel_stds)
        else:
            means_init = ", ".join(["0.0f"] * p.n_features)
            stds_init = ", ".join(["1.0f"] * p.n_features)

        return textwrap.dedent(f"""\
            /* Auto-generated by TimberAccelerate — telemetry preprocessing */
            #include "telemetry_preprocess.h"
            #include <math.h>
            #include <string.h>
            #include <float.h>

            static const float NORM_MEANS[TELEM_N_FEATURES] = {{ {means_init} }};
            static const float NORM_STDS[TELEM_N_FEATURES]  = {{ {stds_init} }};

            void telem_window_init(TelemetryWindow* w) {{
                memset(w, 0, sizeof(TelemetryWindow));
            }}

            int telem_window_push(TelemetryWindow* w,
                                  const float sample[TELEM_N_CHANNELS]) {{
                for (int ch = 0; ch < TELEM_N_CHANNELS; ch++) {{
                    w->buffer[ch][w->write_pos] = sample[ch];
                }}
                w->write_pos = (w->write_pos + 1) % TELEM_WINDOW_SIZE;
                w->samples_received++;

                /* Window is ready when we have enough samples and hit the stride. */
                if (w->samples_received >= TELEM_WINDOW_SIZE &&
                    (w->samples_received % TELEM_STRIDE) == 0) {{
                    return 1;
                }}
                return 0;
            }}

            void telem_extract_features(const TelemetryWindow* w,
                                        float features_out[TELEM_N_FEATURES]) {{
                for (int ch = 0; ch < TELEM_N_CHANNELS; ch++) {{
                    float sum  = 0.0f;
                    float vmin = FLT_MAX;
                    float vmax = -FLT_MAX;

                    for (int i = 0; i < TELEM_WINDOW_SIZE; i++) {{
                        float v = w->buffer[ch][i];
                        sum += v;
                        if (v < vmin) vmin = v;
                        if (v > vmax) vmax = v;
                    }}

                    float mean = sum / TELEM_WINDOW_SIZE;

                    float var_sum = 0.0f;
                    for (int i = 0; i < TELEM_WINDOW_SIZE; i++) {{
                        float diff = w->buffer[ch][i] - mean;
                        var_sum += diff * diff;
                    }}
                    float variance = var_sum / TELEM_WINDOW_SIZE;

                    int base = ch * TELEM_FEATURES_PER_CH;
                    features_out[base + 0] = mean;
                    features_out[base + 1] = variance;
                    features_out[base + 2] = vmin;
                    features_out[base + 3] = vmax;
                }}
            }}

            void telem_normalize(float features[TELEM_N_FEATURES]) {{
                for (int i = 0; i < TELEM_N_FEATURES; i++) {{
                    float std_val = NORM_STDS[i];
                    if (std_val < 1e-12f) std_val = 1.0f;
                    features[i] = (features[i] - NORM_MEANS[i]) / std_val;
                }}
            }}

            int telem_preprocess_sample(TelemetryWindow* w,
                                        const float sample[TELEM_N_CHANNELS],
                                        float features_out[TELEM_N_FEATURES]) {{
                int ready = telem_window_push(w, sample);
                if (ready) {{
                    telem_extract_features(w, features_out);
                    telem_normalize(features_out);
                }}
                return ready;
            }}
        """)
