/* model.h — Timber compiled model inference header */
/* Generated by Timber v0.1 — DO NOT EDIT */

#ifndef TIMBER_MODEL_H
#define TIMBER_MODEL_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

#define TIMBER_N_FEATURES 30
#define TIMBER_N_OUTPUTS  1
#define TIMBER_N_TREES    50
#define TIMBER_MAX_DEPTH  4

/* Opaque context — holds compiled model state. */
/* Read-only after init; thread-safe for concurrent inference. */
typedef struct TimberCtx TimberCtx;

/* Initialize the model context. Call once at startup. */
/* Returns 0 on success, non-zero on error. */
int timber_init(TimberCtx** ctx);

/* Free the model context. */
void timber_free(TimberCtx* ctx);

/* Run inference on a batch of samples. */
/*
 *  inputs:    input feature matrix, row-major, shape [n_samples x 30]
 *  n_samples: number of samples in the batch
 *  outputs:   output buffer, pre-allocated, shape [n_samples x 1]
 *  ctx:       model context from timber_init
 *
 *  Returns 0 on success, non-zero on error.
 */
int timber_infer(
    const float*  inputs,
    int                  n_samples,
    float*        outputs,
    const TimberCtx*     ctx
);

/* Single-sample inference convenience wrapper. */
int timber_infer_single(
    const float  inputs[TIMBER_N_FEATURES],
    float        outputs[TIMBER_N_OUTPUTS],
    const TimberCtx*    ctx
);

#ifdef __cplusplus
}
#endif

#endif /* TIMBER_MODEL_H */
