/* model.c — Timber compiled inference logic */
/* Generated by Timber v0.1 — DO NOT EDIT */

#include "model.h"
#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include <math.h>

#include "model_data.c"

/* Context structure — trivial for static models */
struct TimberCtx {
    int initialized;
};

static struct TimberCtx _default_ctx = {1};

int timber_init(TimberCtx** ctx) {
    if (ctx == NULL) return -1;
    *ctx = &_default_ctx;
    return 0;
}

void timber_free(TimberCtx* ctx) {
    (void)ctx; /* static allocation, nothing to free */
}

static float traverse_tree(
    const float* input,
    const int32_t* features,
    const float* thresholds,
    const int32_t* left_children,
    const int32_t* right_children,
    const float* leaf_values,
    const int8_t* is_leaf,
    const int8_t* default_left,
    int n_nodes
) {
    int node = 0;
    int max_iter = 6;
    while (max_iter-- > 0) {
        if (node < 0 || node >= n_nodes) return 0.0f;
        if (is_leaf[node]) return leaf_values[node];

        int feat = features[node];
        float val = input[feat];

        /* NaN handling: follow default direction */
        if (val != val) { /* NaN check */
            node = default_left[node] ? left_children[node] : right_children[node];
        } else if (val < thresholds[node]) {
            node = left_children[node];
        } else {
            node = right_children[node];
        }
    }
    return 0.0f;
}

static float timber_sigmoid(float x) {
    return 1.0f / (1.0f + expf(-x));
}

int timber_infer_single(
    const float  inputs[TIMBER_N_FEATURES],
    float        outputs[TIMBER_N_OUTPUTS],
    const TimberCtx*    ctx
) {
    (void)ctx;
    float sum = TIMBER_BASE_SCORE;

    sum += traverse_tree(inputs, tree_0_features, tree_0_thresholds, tree_0_left, tree_0_right, tree_0_leaves, tree_0_is_leaf, tree_0_default_left, TREE_0_N_NODES);
    sum += traverse_tree(inputs, tree_1_features, tree_1_thresholds, tree_1_left, tree_1_right, tree_1_leaves, tree_1_is_leaf, tree_1_default_left, TREE_1_N_NODES);
    sum += traverse_tree(inputs, tree_2_features, tree_2_thresholds, tree_2_left, tree_2_right, tree_2_leaves, tree_2_is_leaf, tree_2_default_left, TREE_2_N_NODES);
    sum += traverse_tree(inputs, tree_3_features, tree_3_thresholds, tree_3_left, tree_3_right, tree_3_leaves, tree_3_is_leaf, tree_3_default_left, TREE_3_N_NODES);
    sum += traverse_tree(inputs, tree_4_features, tree_4_thresholds, tree_4_left, tree_4_right, tree_4_leaves, tree_4_is_leaf, tree_4_default_left, TREE_4_N_NODES);
    sum += traverse_tree(inputs, tree_5_features, tree_5_thresholds, tree_5_left, tree_5_right, tree_5_leaves, tree_5_is_leaf, tree_5_default_left, TREE_5_N_NODES);
    sum += traverse_tree(inputs, tree_6_features, tree_6_thresholds, tree_6_left, tree_6_right, tree_6_leaves, tree_6_is_leaf, tree_6_default_left, TREE_6_N_NODES);
    sum += traverse_tree(inputs, tree_7_features, tree_7_thresholds, tree_7_left, tree_7_right, tree_7_leaves, tree_7_is_leaf, tree_7_default_left, TREE_7_N_NODES);
    sum += traverse_tree(inputs, tree_8_features, tree_8_thresholds, tree_8_left, tree_8_right, tree_8_leaves, tree_8_is_leaf, tree_8_default_left, TREE_8_N_NODES);
    sum += traverse_tree(inputs, tree_9_features, tree_9_thresholds, tree_9_left, tree_9_right, tree_9_leaves, tree_9_is_leaf, tree_9_default_left, TREE_9_N_NODES);
    sum += traverse_tree(inputs, tree_10_features, tree_10_thresholds, tree_10_left, tree_10_right, tree_10_leaves, tree_10_is_leaf, tree_10_default_left, TREE_10_N_NODES);
    sum += traverse_tree(inputs, tree_11_features, tree_11_thresholds, tree_11_left, tree_11_right, tree_11_leaves, tree_11_is_leaf, tree_11_default_left, TREE_11_N_NODES);
    sum += traverse_tree(inputs, tree_12_features, tree_12_thresholds, tree_12_left, tree_12_right, tree_12_leaves, tree_12_is_leaf, tree_12_default_left, TREE_12_N_NODES);
    sum += traverse_tree(inputs, tree_13_features, tree_13_thresholds, tree_13_left, tree_13_right, tree_13_leaves, tree_13_is_leaf, tree_13_default_left, TREE_13_N_NODES);
    sum += traverse_tree(inputs, tree_14_features, tree_14_thresholds, tree_14_left, tree_14_right, tree_14_leaves, tree_14_is_leaf, tree_14_default_left, TREE_14_N_NODES);
    sum += traverse_tree(inputs, tree_15_features, tree_15_thresholds, tree_15_left, tree_15_right, tree_15_leaves, tree_15_is_leaf, tree_15_default_left, TREE_15_N_NODES);
    sum += traverse_tree(inputs, tree_16_features, tree_16_thresholds, tree_16_left, tree_16_right, tree_16_leaves, tree_16_is_leaf, tree_16_default_left, TREE_16_N_NODES);
    sum += traverse_tree(inputs, tree_17_features, tree_17_thresholds, tree_17_left, tree_17_right, tree_17_leaves, tree_17_is_leaf, tree_17_default_left, TREE_17_N_NODES);
    sum += traverse_tree(inputs, tree_18_features, tree_18_thresholds, tree_18_left, tree_18_right, tree_18_leaves, tree_18_is_leaf, tree_18_default_left, TREE_18_N_NODES);
    sum += traverse_tree(inputs, tree_19_features, tree_19_thresholds, tree_19_left, tree_19_right, tree_19_leaves, tree_19_is_leaf, tree_19_default_left, TREE_19_N_NODES);
    sum += traverse_tree(inputs, tree_20_features, tree_20_thresholds, tree_20_left, tree_20_right, tree_20_leaves, tree_20_is_leaf, tree_20_default_left, TREE_20_N_NODES);
    sum += traverse_tree(inputs, tree_21_features, tree_21_thresholds, tree_21_left, tree_21_right, tree_21_leaves, tree_21_is_leaf, tree_21_default_left, TREE_21_N_NODES);
    sum += traverse_tree(inputs, tree_22_features, tree_22_thresholds, tree_22_left, tree_22_right, tree_22_leaves, tree_22_is_leaf, tree_22_default_left, TREE_22_N_NODES);
    sum += traverse_tree(inputs, tree_23_features, tree_23_thresholds, tree_23_left, tree_23_right, tree_23_leaves, tree_23_is_leaf, tree_23_default_left, TREE_23_N_NODES);
    sum += traverse_tree(inputs, tree_24_features, tree_24_thresholds, tree_24_left, tree_24_right, tree_24_leaves, tree_24_is_leaf, tree_24_default_left, TREE_24_N_NODES);
    sum += traverse_tree(inputs, tree_25_features, tree_25_thresholds, tree_25_left, tree_25_right, tree_25_leaves, tree_25_is_leaf, tree_25_default_left, TREE_25_N_NODES);
    sum += traverse_tree(inputs, tree_26_features, tree_26_thresholds, tree_26_left, tree_26_right, tree_26_leaves, tree_26_is_leaf, tree_26_default_left, TREE_26_N_NODES);
    sum += traverse_tree(inputs, tree_27_features, tree_27_thresholds, tree_27_left, tree_27_right, tree_27_leaves, tree_27_is_leaf, tree_27_default_left, TREE_27_N_NODES);
    sum += traverse_tree(inputs, tree_28_features, tree_28_thresholds, tree_28_left, tree_28_right, tree_28_leaves, tree_28_is_leaf, tree_28_default_left, TREE_28_N_NODES);
    sum += traverse_tree(inputs, tree_29_features, tree_29_thresholds, tree_29_left, tree_29_right, tree_29_leaves, tree_29_is_leaf, tree_29_default_left, TREE_29_N_NODES);
    sum += traverse_tree(inputs, tree_30_features, tree_30_thresholds, tree_30_left, tree_30_right, tree_30_leaves, tree_30_is_leaf, tree_30_default_left, TREE_30_N_NODES);
    sum += traverse_tree(inputs, tree_31_features, tree_31_thresholds, tree_31_left, tree_31_right, tree_31_leaves, tree_31_is_leaf, tree_31_default_left, TREE_31_N_NODES);
    sum += traverse_tree(inputs, tree_32_features, tree_32_thresholds, tree_32_left, tree_32_right, tree_32_leaves, tree_32_is_leaf, tree_32_default_left, TREE_32_N_NODES);
    sum += traverse_tree(inputs, tree_33_features, tree_33_thresholds, tree_33_left, tree_33_right, tree_33_leaves, tree_33_is_leaf, tree_33_default_left, TREE_33_N_NODES);
    sum += traverse_tree(inputs, tree_34_features, tree_34_thresholds, tree_34_left, tree_34_right, tree_34_leaves, tree_34_is_leaf, tree_34_default_left, TREE_34_N_NODES);
    sum += traverse_tree(inputs, tree_35_features, tree_35_thresholds, tree_35_left, tree_35_right, tree_35_leaves, tree_35_is_leaf, tree_35_default_left, TREE_35_N_NODES);
    sum += traverse_tree(inputs, tree_36_features, tree_36_thresholds, tree_36_left, tree_36_right, tree_36_leaves, tree_36_is_leaf, tree_36_default_left, TREE_36_N_NODES);
    sum += traverse_tree(inputs, tree_37_features, tree_37_thresholds, tree_37_left, tree_37_right, tree_37_leaves, tree_37_is_leaf, tree_37_default_left, TREE_37_N_NODES);
    sum += traverse_tree(inputs, tree_38_features, tree_38_thresholds, tree_38_left, tree_38_right, tree_38_leaves, tree_38_is_leaf, tree_38_default_left, TREE_38_N_NODES);
    sum += traverse_tree(inputs, tree_39_features, tree_39_thresholds, tree_39_left, tree_39_right, tree_39_leaves, tree_39_is_leaf, tree_39_default_left, TREE_39_N_NODES);
    sum += traverse_tree(inputs, tree_40_features, tree_40_thresholds, tree_40_left, tree_40_right, tree_40_leaves, tree_40_is_leaf, tree_40_default_left, TREE_40_N_NODES);
    sum += traverse_tree(inputs, tree_41_features, tree_41_thresholds, tree_41_left, tree_41_right, tree_41_leaves, tree_41_is_leaf, tree_41_default_left, TREE_41_N_NODES);
    sum += traverse_tree(inputs, tree_42_features, tree_42_thresholds, tree_42_left, tree_42_right, tree_42_leaves, tree_42_is_leaf, tree_42_default_left, TREE_42_N_NODES);
    sum += traverse_tree(inputs, tree_43_features, tree_43_thresholds, tree_43_left, tree_43_right, tree_43_leaves, tree_43_is_leaf, tree_43_default_left, TREE_43_N_NODES);
    sum += traverse_tree(inputs, tree_44_features, tree_44_thresholds, tree_44_left, tree_44_right, tree_44_leaves, tree_44_is_leaf, tree_44_default_left, TREE_44_N_NODES);
    sum += traverse_tree(inputs, tree_45_features, tree_45_thresholds, tree_45_left, tree_45_right, tree_45_leaves, tree_45_is_leaf, tree_45_default_left, TREE_45_N_NODES);
    sum += traverse_tree(inputs, tree_46_features, tree_46_thresholds, tree_46_left, tree_46_right, tree_46_leaves, tree_46_is_leaf, tree_46_default_left, TREE_46_N_NODES);
    sum += traverse_tree(inputs, tree_47_features, tree_47_thresholds, tree_47_left, tree_47_right, tree_47_leaves, tree_47_is_leaf, tree_47_default_left, TREE_47_N_NODES);
    sum += traverse_tree(inputs, tree_48_features, tree_48_thresholds, tree_48_left, tree_48_right, tree_48_leaves, tree_48_is_leaf, tree_48_default_left, TREE_48_N_NODES);
    sum += traverse_tree(inputs, tree_49_features, tree_49_thresholds, tree_49_left, tree_49_right, tree_49_leaves, tree_49_is_leaf, tree_49_default_left, TREE_49_N_NODES);

    outputs[0] = timber_sigmoid(sum);

    return 0;
}

int timber_infer(
    const float*  inputs,
    int                  n_samples,
    float*        outputs,
    const TimberCtx*     ctx
) {
    int i;
    if (inputs == NULL || outputs == NULL) return -1;
    if (n_samples <= 0) return -1;

    for (i = 0; i < n_samples; i++) {
        int rc = timber_infer_single(
            inputs + i * TIMBER_N_FEATURES,
            outputs + i * TIMBER_N_OUTPUTS,
            ctx
        );
        if (rc != 0) return rc;
    }
    return 0;
}
