/* model_data.c — Timber compiled model data */
/* Generated by Timber v0.1 — DO NOT EDIT */

#include "model.h"
#include <math.h>

static const int32_t tree_0_features[13] = {27, 23, 20, 13, 26, -1, -1, 1, -1, -1, -1, -1, -1};
static const float tree_0_thresholds[13] = {0.1424f, 967.0f, 14.85f, 43.14f, 0.1935f, 0.0f, 0.0f, 22.47f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_0_left[13] = {1, 3, 5, 7, 9, -1, -1, 11, -1, -1, -1, -1, -1};
static const int32_t tree_0_right[13] = {2, 4, 6, 8, 10, -1, -1, 12, -1, -1, -1, -1, -1};
static const float tree_0_leaves[13] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.011055535f, -0.25256354f, 0.0f, -0.021189794f, -0.0065913424f, -0.20942883f, 0.15463917f, 0.07674655f};
static const int8_t tree_0_is_leaf[13] = {0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1};
static const int8_t tree_0_default_left[13] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_0_N_NODES 13

static const int32_t tree_1_features[21] = {7, 20, 22, 12, 1, 21, 21, 24, -1, -1, 1, -1, -1, 7, -1, -1, -1, -1, -1, -1, -1};
static const float tree_1_thresholds[21] = {0.05074f, 16.84f, 102.2f, 4.106f, 15.73f, 25.48f, 19.29f, 0.1665f, 0.0f, 0.0f, 19.54f, 0.0f, 0.0f, 0.08591f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_1_left[21] = {1, 3, 5, 7, 9, 11, 13, 15, -1, -1, 17, -1, -1, 19, -1, -1, -1, -1, -1, -1, -1};
static const int32_t tree_1_right[21] = {2, 4, 6, 8, 10, 12, 14, 16, -1, -1, 18, -1, -1, 20, -1, -1, -1, -1, -1, -1, -1};
static const float tree_1_leaves[21] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -0.009237081f, 0.087398164f, 0.0f, 0.1091084f, -0.09613953f, 0.0f, -0.22387509f, 0.1452118f, 0.03704555f, -0.0449973f, -0.16584405f, 0.100216344f, -0.13783807f};
static const int8_t tree_1_is_leaf[21] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1};
static const int8_t tree_1_default_left[21] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_1_N_NODES 21

static const int32_t tree_2_features[21] = {7, 20, 27, 12, 1, 21, 16, 29, -1, -1, 20, -1, 0, -1, -1, -1, -1, -1, -1, -1, -1};
static const float tree_2_thresholds[21] = {0.05074f, 16.84f, 0.1466f, 4.106f, 15.73f, 22.88f, 0.0996f, 0.1178f, 0.0f, 0.0f, 18.07f, 0.0f, 13.54f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_2_left[21] = {1, 3, 5, 7, 9, 11, 13, 15, -1, -1, 17, -1, 19, -1, -1, -1, -1, -1, -1, -1, -1};
static const int32_t tree_2_right[21] = {2, 4, 6, 8, 10, 12, 14, 16, -1, -1, 18, -1, 20, -1, -1, -1, -1, -1, -1, -1, -1};
static const float tree_2_leaves[21] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -0.008730338f, 0.083836704f, 0.0f, 0.11262133f, 0.0f, -0.20031114f, -0.0317219f, 0.13816303f, 0.031973474f, -0.1539384f, -0.039986413f, 0.044181697f, -0.17328358f};
static const int8_t tree_2_is_leaf[21] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1};
static const int8_t tree_2_default_left[21] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_2_N_NODES 21

static const int32_t tree_3_features[19] = {7, 20, 22, 13, 1, 21, 21, 24, -1, -1, -1, -1, -1, 7, -1, -1, -1, -1, -1};
static const float tree_3_thresholds[19] = {0.05074f, 16.84f, 102.2f, 42.76f, 18.3f, 25.48f, 19.29f, 0.1665f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.08591f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_3_left[19] = {1, 3, 5, 7, 9, 11, 13, 15, -1, -1, -1, -1, -1, 17, -1, -1, -1, -1, -1};
static const int32_t tree_3_right[19] = {2, 4, 6, 8, 10, 12, 14, 16, -1, -1, -1, -1, -1, 18, -1, -1, -1, -1, -1};
static const float tree_3_leaves[19] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -0.010906911f, 0.061368335f, -0.1330231f, 0.100928284f, -0.083630584f, 0.0f, -0.18002766f, 0.13224797f, 0.02993312f, 0.09102633f, -0.11619692f};
static const int8_t tree_3_is_leaf[19] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1};
static const int8_t tree_3_default_left[19] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_3_N_NODES 19

static const int32_t tree_4_features[21] = {7, 20, 27, 12, 1, 21, 19, 5, -1, -1, 17, -1, 0, -1, -1, -1, -1, -1, -1, -1, -1};
static const float tree_4_thresholds[21] = {0.05074f, 16.84f, 0.1466f, 4.106f, 15.73f, 22.88f, 0.009368f, 0.1348f, 0.0f, 0.0f, 0.009233f, 0.0f, 13.54f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_4_left[21] = {1, 3, 5, 7, 9, 11, 13, 15, -1, -1, 17, -1, 19, -1, -1, -1, -1, -1, -1, -1, -1};
static const int32_t tree_4_right[21] = {2, 4, 6, 8, 10, 12, 14, 16, -1, -1, 18, -1, 20, -1, -1, -1, -1, -1, -1, -1, -1};
static const float tree_4_leaves[21] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -0.010677047f, 0.07823203f, 0.0f, 0.103567556f, 0.0f, -0.16812114f, -0.021203695f, 0.12722814f, 0.024392916f, -0.13633674f, -0.030135712f, 0.040589683f, -0.14552253f};
static const int8_t tree_4_is_leaf[21] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1};
static const int8_t tree_4_default_left[21] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_4_N_NODES 21

static const int32_t tree_5_features[19] = {7, 20, 22, 13, 1, 21, -1, 21, -1, -1, 20, 28, -1, -1, -1, -1, -1, -1, -1};
static const float tree_5_thresholds[19] = {0.05074f, 16.84f, 114.6f, 42.76f, 15.73f, 25.48f, 0.0f, 33.21f, 0.0f, 0.0f, 18.07f, 0.3124f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_5_left[19] = {1, 3, 5, 7, 9, 11, -1, 13, -1, -1, 15, 17, -1, -1, -1, -1, -1, -1, -1};
static const int32_t tree_5_right[19] = {2, 4, 6, 8, 10, 12, -1, 14, -1, -1, 16, 18, -1, -1, -1, -1, -1, -1, -1};
static const float tree_5_leaves[19] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -0.15704845f, 0.0f, -0.012571155f, 0.075357586f, 0.0f, 0.0f, -0.13518617f, 0.12483703f, 0.050447058f, -0.12836848f, -0.027066577f, 0.11131348f, -0.00016107589f};
static const int8_t tree_5_is_leaf[19] = {0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1};
static const int8_t tree_5_default_left[19] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_5_N_NODES 19

static const int32_t tree_6_features[21] = {7, 20, 22, 12, 1, 21, 21, 14, -1, -1, -1, -1, -1, 7, 4, -1, -1, -1, -1, -1, -1};
static const float tree_6_thresholds[21] = {0.05074f, 16.84f, 102.2f, 4.106f, 18.3f, 25.48f, 19.29f, 0.003338f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.08591f, 0.08369f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_6_left[21] = {1, 3, 5, 7, 9, 11, 13, 15, -1, -1, -1, -1, -1, 17, 19, -1, -1, -1, -1, -1, -1};
static const int32_t tree_6_right[21] = {2, 4, 6, 8, 10, 12, 14, 16, -1, -1, -1, -1, -1, 18, 20, -1, -1, -1, -1, -1, -1};
static const float tree_6_leaves[21] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -0.012230575f, 0.055998545f, -0.10953162f, 0.09023221f, -0.06642216f, 0.0f, 0.0f, 0.020643486f, 0.11936213f, 0.08032256f, -0.0937235f, -0.04212117f, -0.14887688f};
static const int8_t tree_6_is_leaf[21] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1};
static const int8_t tree_6_default_left[21] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_6_N_NODES 21

static const int32_t tree_7_features[17] = {22, 7, 26, 13, -1, 1, 21, -1, -1, -1, -1, 7, 24, -1, -1, -1, -1};
static const float tree_7_thresholds[17] = {101.7f, 0.05669f, 0.2085f, 40.09f, 0.0f, 19.54f, 19.62f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0734f, 0.1028f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_7_left[17] = {1, 3, 5, 7, -1, 9, 11, -1, -1, -1, -1, 13, 15, -1, -1, -1, -1};
static const int32_t tree_7_right[17] = {2, 4, 6, 8, -1, 10, 12, -1, -1, -1, -1, 14, 16, -1, -1, -1, -1};
static const float tree_7_leaves[17] = {0.0f, 0.0f, 0.0f, 0.0f, -0.031751644f, 0.0f, 0.0f, 0.1185023f, -0.017996436f, 0.101593666f, -0.0434333f, 0.0f, 0.0f, 0.08958093f, -0.0896174f, 0.0010550518f, -0.13878457f};
static const int8_t tree_7_is_leaf[17] = {0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1};
static const int8_t tree_7_default_left[17] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_7_N_NODES 17

static const int32_t tree_8_features[19] = {7, 20, 22, 13, 1, 21, -1, 21, -1, -1, 17, 4, -1, -1, -1, -1, -1, -1, -1};
static const float tree_8_thresholds[19] = {0.05074f, 16.84f, 114.6f, 42.76f, 15.73f, 25.48f, 0.0f, 33.21f, 0.0f, 0.0f, 0.009233f, 0.1158f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_8_left[19] = {1, 3, 5, 7, 9, 11, -1, 13, -1, -1, 15, 17, -1, -1, -1, -1, -1, -1, -1};
static const int32_t tree_8_right[19] = {2, 4, 6, 8, 10, 12, -1, 14, -1, -1, 16, 18, -1, -1, -1, -1, -1, -1, -1};
static const float tree_8_leaves[19] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -0.13536471f, 0.0f, -0.014028834f, 0.06757173f, 0.0f, 0.0f, -0.11405512f, 0.115198255f, 0.03564343f, -0.11189637f, -0.017326627f, 0.1016228f, 0.010300552f};
static const int8_t tree_8_is_leaf[19] = {0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1};
static const int8_t tree_8_default_left[19] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_8_N_NODES 19

static const int32_t tree_9_features[17] = {22, 7, 26, 13, -1, 1, 21, -1, -1, -1, -1, 7, 24, -1, -1, -1, -1};
static const float tree_9_thresholds[17] = {101.7f, 0.05669f, 0.2085f, 40.09f, 0.0f, 19.54f, 19.62f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0734f, 0.1028f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_9_left[17] = {1, 3, 5, 7, -1, 9, 11, -1, -1, -1, -1, 13, 15, -1, -1, -1, -1};
static const int32_t tree_9_right[17] = {2, 4, 6, 8, -1, 10, 12, -1, -1, -1, -1, 14, 16, -1, -1, -1, -1};
static const float tree_9_leaves[17] = {0.0f, 0.0f, 0.0f, 0.0f, -0.028189136f, 0.0f, 0.0f, 0.1130321f, -0.017284866f, 0.09585454f, -0.039481923f, 0.0f, 0.0f, 0.08324634f, -0.08050919f, 0.0014108017f, -0.12743102f};
static const int8_t tree_9_is_leaf[17] = {0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1};
static const int8_t tree_9_default_left[17] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_9_N_NODES 17

static const int32_t tree_10_features[19] = {27, 20, 16, 13, 1, 10, -1, 21, -1, -1, 11, -1, 26, -1, -1, -1, -1, -1, -1};
static const float tree_10_thresholds[19] = {0.1418f, 16.84f, 0.1166f, 48.55f, 16.16f, 0.2137f, 0.0f, 30.12f, 0.0f, 0.0f, 1.35f, 0.0f, 0.256f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_10_left[19] = {1, 3, 5, 7, 9, 11, -1, 13, -1, -1, 15, -1, 17, -1, -1, -1, -1, -1, -1};
static const int32_t tree_10_right[19] = {2, 4, 6, 8, 10, 12, -1, 14, -1, -1, 16, -1, 18, -1, -1, -1, -1, -1, -1};
static const float tree_10_leaves[19] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.027225753f, 0.0f, -0.017669175f, 0.07031306f, 0.0f, -0.011767184f, 0.0f, 0.113562874f, 0.050489753f, -0.11831912f, -0.0052389726f, -0.029706825f, -0.12692694f};
static const int8_t tree_10_is_leaf[19] = {0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1};
static const int8_t tree_10_default_left[19] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_10_N_NODES 19

static const int32_t tree_11_features[17] = {22, 7, 26, 12, -1, 9, 21, -1, -1, -1, -1, 7, 24, -1, -1, -1, -1};
static const float tree_11_thresholds[17] = {101.7f, 0.05669f, 0.2085f, 4.106f, 0.0f, 0.05318f, 19.62f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0734f, 0.1094f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_11_left[17] = {1, 3, 5, 7, -1, 9, 11, -1, -1, -1, -1, 13, 15, -1, -1, -1, -1};
static const int32_t tree_11_right[17] = {2, 4, 6, 8, -1, 10, 12, -1, -1, -1, -1, 14, 16, -1, -1, -1, -1};
static const float tree_11_leaves[17] = {0.0f, 0.0f, 0.0f, 0.0f, -0.025119925f, 0.0f, 0.0f, 0.10850006f, -0.017930878f, -0.013755423f, 0.084584326f, 0.0f, 0.0f, 0.07861061f, -0.07348778f, -0.015157479f, -0.1211197f};
static const int8_t tree_11_is_leaf[17] = {0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1};
static const int8_t tree_11_default_left[17] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_11_N_NODES 17

static const int32_t tree_12_features[15] = {23, 27, 26, 21, -1, -1, 10, 10, 26, -1, -1, -1, -1, -1, -1};
static const float tree_12_thresholds[15] = {876.5f, 0.1583f, 0.2177f, 30.12f, 0.0f, 0.0f, 0.2451f, 0.5506f, 0.1935f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_12_left[15] = {1, 3, 5, 7, -1, -1, 9, 11, 13, -1, -1, -1, -1, -1, -1};
static const int32_t tree_12_right[15] = {2, 4, 6, 8, -1, -1, 10, 12, 14, -1, -1, -1, -1, -1, -1};
static const float tree_12_leaves[15] = {0.0f, 0.0f, 0.0f, 0.0f, -0.09341895f, 0.014887625f, 0.0f, 0.0f, 0.0f, -0.018052869f, -0.12074902f, 0.11047155f, -0.01197326f, 0.08784442f, -0.071469165f};
static const int8_t tree_12_is_leaf[15] = {0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1};
static const int8_t tree_12_default_left[15] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_12_N_NODES 15

static const int32_t tree_13_features[17] = {7, 20, 22, 12, 1, 21, -1, 21, -1, -1, -1, 24, -1, -1, -1, -1, -1};
static const float tree_13_thresholds[17] = {0.05074f, 16.84f, 114.6f, 4.106f, 19.54f, 25.48f, 0.0f, 33.37f, 0.0f, 0.0f, 0.0f, 0.146f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_13_left[17] = {1, 3, 5, 7, 9, 11, -1, 13, -1, -1, -1, 15, -1, -1, -1, -1, -1};
static const int32_t tree_13_right[17] = {2, 4, 6, 8, 10, 12, -1, 14, -1, -1, -1, 16, -1, -1, -1, -1, -1};
static const float tree_13_leaves[17] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -0.116303675f, 0.0f, -0.018425742f, 0.032448225f, -0.09159754f, 0.0f, -0.09480683f, 0.10473996f, 0.020783229f, 0.089074634f, 0.018097896f};
static const int8_t tree_13_is_leaf[17] = {0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1};
static const int8_t tree_13_default_left[17] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_13_N_NODES 17

static const int32_t tree_14_features[19] = {22, 7, 27, 13, -1, 1, 4, 21, -1, 20, 20, -1, -1, -1, -1, -1, -1, -1, -1};
static const float tree_14_thresholds[19] = {101.7f, 0.05669f, 0.1453f, 40.09f, 0.0f, 18.3f, 0.09029f, 33.21f, 0.0f, 17.39f, 16.77f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_14_left[19] = {1, 3, 5, 7, -1, 9, 11, 13, -1, 15, 17, -1, -1, -1, -1, -1, -1, -1, -1};
static const int32_t tree_14_right[19] = {2, 4, 6, 8, -1, 10, 12, 14, -1, 16, 18, -1, -1, -1, -1, -1, -1, -1, -1};
static const float tree_14_leaves[19] = {0.0f, 0.0f, 0.0f, 0.0f, -0.021856492f, 0.0f, 0.0f, 0.0f, -0.020419149f, 0.0f, 0.0f, -0.026907125f, -0.11446368f, 0.10652997f, 0.039422456f, 0.084210746f, 0.017026251f, 0.0114605315f, -0.09297708f};
static const int8_t tree_14_is_leaf[19] = {0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1};
static const int8_t tree_14_default_left[19] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_14_N_NODES 19

static const int32_t tree_15_features[17] = {27, 20, 16, 28, 1, 10, -1, -1, 21, -1, 11, -1, -1, -1, -1, -1, -1};
static const float tree_15_thresholds[17] = {0.1424f, 16.84f, 0.1166f, 0.1987f, 16.16f, 0.2137f, 0.0f, 0.0f, 30.12f, 0.0f, 1.336f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_15_left[17] = {1, 3, 5, 7, 9, 11, -1, -1, 13, -1, 15, -1, -1, -1, -1, -1, -1};
static const int32_t tree_15_right[17] = {2, 4, 6, 8, 10, 12, -1, -1, 14, -1, 16, -1, -1, -1, -1, -1, -1};
static const float tree_15_leaves[17] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.03071374f, -0.012214544f, 0.0f, 0.062439848f, 0.0f, -0.0070773326f, -0.11066214f, 0.106269196f, 0.037241653f, -0.0998609f, -0.00757742f};
static const int8_t tree_15_is_leaf[17] = {0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1};
static const int8_t tree_15_default_left[17] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_15_N_NODES 17

static const int32_t tree_16_features[19] = {7, 20, 22, 13, 1, 21, -1, 14, 19, -1, -1, 24, -1, -1, -1, -1, -1, -1, -1};
static const float tree_16_thresholds[19] = {0.05074f, 16.84f, 114.6f, 34.44f, 19.54f, 25.48f, 0.0f, 0.003629f, 0.003211f, 0.0f, 0.0f, 0.1389f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_16_left[19] = {1, 3, 5, 7, 9, 11, -1, 13, 15, -1, -1, 17, -1, -1, -1, -1, -1, -1, -1};
static const int32_t tree_16_right[19] = {2, 4, 6, 8, 10, 12, -1, 14, 16, -1, -1, 18, -1, -1, -1, -1, -1, -1, -1};
static const float tree_16_leaves[19] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -0.10918092f, 0.0f, 0.0f, 0.03199385f, -0.08111121f, 0.0f, -0.086251274f, 0.0073915846f, 0.09991206f, -0.026746526f, 0.027028931f, 0.08210129f, 0.021969168f};
static const int8_t tree_16_is_leaf[19] = {0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1};
static const int8_t tree_16_default_left[19] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_16_N_NODES 19

static const int32_t tree_17_features[19] = {22, 7, 26, 28, -1, 1, 21, -1, 21, -1, -1, 7, 24, -1, -1, -1, -1, -1, -1};
static const float tree_17_thresholds[19] = {101.7f, 0.05669f, 0.2085f, 0.1987f, 0.0f, 19.31f, 19.62f, 0.0f, 33.37f, 0.0f, 0.0f, 0.06254f, 0.1094f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_17_left[19] = {1, 3, 5, 7, -1, 9, 11, -1, 13, -1, -1, 15, 17, -1, -1, -1, -1, -1, -1};
static const int32_t tree_17_right[19] = {2, 4, 6, 8, -1, 10, 12, -1, 14, -1, -1, 16, 18, -1, -1, -1, -1, -1, -1};
static const float tree_17_leaves[19] = {0.0f, 0.0f, 0.0f, 0.0f, -0.018837584f, 0.0f, 0.0f, -0.014285351f, 0.0f, 0.07295615f, -0.00875784f, 0.0f, 0.0f, 0.10364242f, 0.031611666f, 0.062105328f, -0.036289293f, -0.007179379f, -0.106732525f};
static const int8_t tree_17_is_leaf[19] = {0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1};
static const int8_t tree_17_default_left[19] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_17_N_NODES 19

static const int32_t tree_18_features[15] = {23, 27, 26, 1, -1, -1, 1, 28, 20, -1, -1, -1, -1, -1, -1};
static const float tree_18_thresholds[15] = {876.5f, 0.1583f, 0.2177f, 21.35f, 0.0f, 0.0f, 15.6f, 0.1987f, 14.44f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_18_left[15] = {1, 3, 5, 7, -1, -1, 9, 11, 13, -1, -1, -1, -1, -1, -1};
static const int32_t tree_18_right[15] = {2, 4, 6, 8, -1, -1, 10, 12, 14, -1, -1, -1, -1, -1, -1};
static const float tree_18_leaves[15] = {0.0f, 0.0f, 0.0f, 0.0f, -0.07807363f, 0.017636262f, 0.0f, 0.0f, 0.0f, -0.018053308f, -0.10697346f, 0.013024879f, 0.103082776f, 0.07191079f, -0.064991824f};
static const int8_t tree_18_is_leaf[15] = {0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1};
static const int8_t tree_18_default_left[15] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_18_N_NODES 15

static const int32_t tree_19_features[17] = {7, 3, 22, 21, 1, 21, -1, 12, 20, -1, -1, -1, -1, -1, -1, -1, -1};
static const float tree_19_thresholds[17] = {0.05252f, 698.8f, 114.6f, 29.87f, 19.54f, 25.48f, 0.0f, 3.466f, 14.38f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_19_left[17] = {1, 3, 5, 7, 9, 11, -1, 13, 15, -1, -1, -1, -1, -1, -1, -1, -1};
static const int32_t tree_19_right[17] = {2, 4, 6, 8, 10, 12, -1, 14, 16, -1, -1, -1, -1, -1, -1, -1, -1};
static const float tree_19_leaves[17] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -0.10364421f, 0.0f, 0.0f, 0.025891054f, -0.0813395f, 0.066141695f, -0.079297446f, 0.100143276f, 0.009506479f, 0.07624655f, -0.052661788f};
static const int8_t tree_19_is_leaf[17] = {0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1};
static const int8_t tree_19_default_left[17] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_19_N_NODES 17

static const int32_t tree_20_features[17] = {27, 3, 20, 21, 1, 27, -1, 11, 26, -1, -1, -1, -1, -1, -1, -1, -1};
static const float tree_20_thresholds[17] = {0.1424f, 698.8f, 15.34f, 29.87f, 18.3f, 0.1564f, 0.0f, 1.978f, 0.1935f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_20_left[17] = {1, 3, 5, 7, 9, 11, -1, 13, 15, -1, -1, -1, -1, -1, -1, -1, -1};
static const int32_t tree_20_right[17] = {2, 4, 6, 8, 10, 12, -1, 14, 16, -1, -1, -1, -1, -1, -1, -1, -1};
static const float tree_20_leaves[17] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -0.099444896f, 0.0f, 0.0f, 0.033843733f, -0.07739221f, 0.03594783f, -0.031035496f, 0.10046667f, 0.0134134935f, 0.07503494f, -0.050599705f};
static const int8_t tree_20_is_leaf[17] = {0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1};
static const int8_t tree_20_default_left[17] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_20_N_NODES 17

static const int32_t tree_21_features[19] = {7, 20, 19, 28, 1, 21, -1, -1, 21, 26, 17, -1, -1, -1, -1, -1, -1, -1, -1};
static const float tree_21_thresholds[19] = {0.05596f, 15.63f, 0.01148f, 0.1987f, 19.63f, 19.29f, 0.0f, 0.0f, 33.37f, 0.2177f, 0.0113f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_21_left[19] = {1, 3, 5, 7, 9, 11, -1, -1, 13, 15, 17, -1, -1, -1, -1, -1, -1, -1, -1};
static const int32_t tree_21_right[19] = {2, 4, 6, 8, 10, 12, -1, -1, 14, 16, 18, -1, -1, -1, -1, -1, -1, -1, -1};
static const float tree_21_leaves[19] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.031639278f, -0.017689357f, 0.0f, 0.0f, 0.0f, -0.003183291f, -0.10026621f, 0.09931201f, 0.024093254f, 0.07732906f, 0.0014883168f, -0.096531704f, -0.00027488064f};
static const int8_t tree_21_is_leaf[19] = {0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1};
static const int8_t tree_21_default_left[19] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_21_N_NODES 19

static const int32_t tree_22_features[15] = {23, 27, 6, 1, -1, 1, -1, 28, 20, -1, -1, -1, -1, -1, -1};
static const float tree_22_thresholds[15] = {876.5f, 0.1583f, 0.0716f, 21.35f, 0.0f, 19.54f, 0.0f, 0.2048f, 14.44f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_22_left[15] = {1, 3, 5, 7, -1, 9, -1, 11, 13, -1, -1, -1, -1, -1, -1};
static const int32_t tree_22_right[15] = {2, 4, 6, 8, -1, 10, -1, 12, 14, -1, -1, -1, -1, -1, -1};
static const float tree_22_leaves[15] = {0.0f, 0.0f, 0.0f, 0.0f, -0.06894863f, 0.0f, -0.10018587f, 0.0f, 0.0f, 0.056445427f, -0.06341833f, 0.01429866f, 0.098549634f, 0.06358223f, -0.055652834f};
static const int8_t tree_22_is_leaf[15] = {0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1};
static const int8_t tree_22_default_left[15] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_22_N_NODES 15

static const int32_t tree_23_features[17] = {27, 3, 20, 21, 1, -1, 13, 11, 26, -1, -1, -1, -1, -1, -1, -1, -1};
static const float tree_23_thresholds[17] = {0.1424f, 698.8f, 15.34f, 29.87f, 18.3f, 0.0f, 25.06f, 1.931f, 0.1935f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_23_left[17] = {1, 3, 5, 7, 9, -1, 11, 13, 15, -1, -1, -1, -1, -1, -1, -1, -1};
static const int32_t tree_23_right[17] = {2, 4, 6, 8, 10, -1, 12, 14, 16, -1, -1, -1, -1, -1, -1, -1, -1};
static const float tree_23_leaves[17] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0025486334f, 0.0f, 0.0f, 0.0f, 0.03071717f, -0.07029683f, -0.028909354f, -0.09849046f, 0.09702301f, 0.012752727f, 0.07063113f, -0.04479378f};
static const int8_t tree_23_is_leaf[17] = {0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1};
static const int8_t tree_23_default_left[17] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_23_N_NODES 17

static const int32_t tree_24_features[15] = {7, 13, 19, 14, 24, 21, -1, -1, 21, -1, -1, -1, -1, -1, -1};
static const float tree_24_thresholds[15] = {0.05596f, 34.44f, 0.01148f, 0.003418f, 0.1048f, 19.29f, 0.0f, 0.0f, 33.21f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_24_left[15] = {1, 3, 5, 7, 9, 11, -1, -1, 13, -1, -1, -1, -1, -1, -1};
static const int32_t tree_24_right[15] = {2, 4, 6, 8, 10, 12, -1, -1, 14, -1, -1, -1, -1, -1, -1};
static const float tree_24_leaves[15] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.029536733f, -0.03861462f, 0.0f, 0.03873094f, -0.071411364f, -0.0015318298f, -0.09602941f, 0.090492055f, 0.009210123f};
static const int8_t tree_24_is_leaf[15] = {0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1};
static const int8_t tree_24_default_left[15] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_24_N_NODES 15

static const int32_t tree_25_features[15] = {27, 3, 20, 21, 1, -1, -1, 11, 26, -1, -1, -1, -1, -1, -1};
static const float tree_25_thresholds[15] = {0.1515f, 698.8f, 15.29f, 29.87f, 19.54f, 0.0f, 0.0f, 1.924f, 0.1935f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_25_left[15] = {1, 3, 5, 7, 9, -1, -1, 11, 13, -1, -1, -1, -1, -1, -1};
static const int32_t tree_25_right[15] = {2, 4, 6, 8, 10, -1, -1, 12, 14, -1, -1, -1, -1, -1, -1};
static const float tree_25_leaves[15] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -0.015231529f, -0.09444591f, 0.0f, 0.0f, 0.018167803f, -0.082707725f, 0.09628737f, 0.011956732f, 0.06751937f, -0.059337217f};
static const int8_t tree_25_is_leaf[15] = {0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1};
static const int8_t tree_25_default_left[15] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_25_N_NODES 15

static const int32_t tree_26_features[17] = {27, 0, 22, 28, -1, 21, -1, -1, 21, 28, 18, -1, -1, -1, -1, -1, -1};
static const float tree_26_thresholds[17] = {0.1112f, 14.99f, 116.2f, 0.2107f, 0.0f, 27.37f, 0.0f, 0.0f, 33.37f, 0.3109f, 0.01879f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_26_left[17] = {1, 3, 5, 7, -1, 9, -1, -1, 11, 13, 15, -1, -1, -1, -1, -1, -1};
static const int32_t tree_26_right[17] = {2, 4, 6, 8, -1, 10, -1, -1, 12, 14, 16, -1, -1, -1, -1, -1, -1};
static const float tree_26_leaves[17] = {0.0f, 0.0f, 0.0f, 0.0f, -0.023236314f, 0.0f, -0.0940403f, 0.013335568f, 0.0f, 0.0f, 0.0f, 0.09290514f, 0.01810376f, 0.07454918f, -0.002819917f, -0.08563953f, 0.0035024618f};
static const int8_t tree_26_is_leaf[17] = {0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1};
static const int8_t tree_26_default_left[17] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_26_N_NODES 17

static const int32_t tree_27_features[15] = {27, 3, 2, 21, 1, -1, -1, 11, 27, -1, -1, -1, -1, -1, -1};
static const float tree_27_thresholds[15] = {0.1515f, 698.8f, 85.09f, 29.87f, 19.54f, 0.0f, 0.0f, 1.911f, 0.0875f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_27_left[15] = {1, 3, 5, 7, 9, -1, -1, 11, 13, -1, -1, -1, -1, -1, -1};
static const int32_t tree_27_right[15] = {2, 4, 6, 8, 10, -1, -1, 12, 14, -1, -1, -1, -1, -1, -1};
static const float tree_27_leaves[15] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -0.016946493f, -0.091479205f, 0.0f, 0.0f, 0.01884277f, -0.07916541f, 0.09358597f, 0.012185632f, 0.06520777f, -0.05377503f};
static const int8_t tree_27_is_leaf[15] = {0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1};
static const int8_t tree_27_default_left[15] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_27_N_NODES 15

static const int32_t tree_28_features[19] = {7, 15, 21, 16, 28, 27, 22, -1, 1, 18, -1, -1, -1, -1, -1, -1, -1, -1, -1};
static const float tree_28_thresholds[19] = {0.05074f, 0.01203f, 23.84f, 0.01246f, 0.3215f, 0.1583f, 99.43f, 0.0f, 20.97f, 0.01466f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_28_left[19] = {1, 3, 5, 7, 9, 11, 13, -1, 15, 17, -1, -1, -1, -1, -1, -1, -1, -1, -1};
static const int32_t tree_28_right[19] = {2, 4, 6, 8, 10, 12, 14, -1, 16, 18, -1, -1, -1, -1, -1, -1, -1, -1, -1};
static const float tree_28_leaves[19] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.06980373f, 0.0f, 0.0f, -0.009605959f, 0.05715629f, -0.055324372f, -0.018805424f, -0.09182802f, -0.013673164f, -0.105718635f, 0.03209574f, 0.09524916f};
static const int8_t tree_28_is_leaf[19] = {0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1};
static const int8_t tree_28_default_left[19] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_28_N_NODES 19

static const int32_t tree_29_features[13] = {26, 13, 20, -1, -1, 4, 21, -1, -1, -1, 24, -1, -1};
static const float tree_29_thresholds[13] = {0.2085f, 42.76f, 14.49f, 0.0f, 0.0f, 0.1068f, 19.71f, 0.0f, 0.0f, 0.0f, 0.1084f, 0.0f, 0.0f};
static const int32_t tree_29_left[13] = {1, 3, 5, -1, -1, 7, 9, -1, -1, -1, 11, -1, -1};
static const int32_t tree_29_right[13] = {2, 4, 6, -1, -1, 8, 10, -1, -1, -1, 12, -1, -1};
static const float tree_29_leaves[13] = {0.0f, 0.0f, 0.0f, 0.09065205f, -0.022715783f, 0.0f, 0.0f, 0.065262124f, -0.00701496f, 0.018929575f, 0.0f, 0.0072485134f, -0.08893737f};
static const int8_t tree_29_is_leaf[13] = {0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1};
static const int8_t tree_29_default_left[13] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_29_N_NODES 13

static const int32_t tree_30_features[15] = {27, 13, 20, 21, 24, -1, -1, 2, 1, -1, -1, -1, -1, -1, -1};
static const float tree_30_thresholds[15] = {0.1515f, 34.44f, 15.49f, 30.12f, 0.1048f, 0.0f, 0.0f, 98.64f, 23.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_30_left[15] = {1, 3, 5, 7, 9, -1, -1, 11, 13, -1, -1, -1, -1, -1, -1};
static const int32_t tree_30_right[15] = {2, 4, 6, 8, 10, -1, -1, 12, 14, -1, -1, -1, -1, -1, -1};
static const float tree_30_leaves[15] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -0.017076105f, -0.08712084f, 0.0f, 0.0f, 0.024466487f, -0.063800834f, 0.090471454f, 0.005328031f, -0.062175103f, 0.05832333f};
static const int8_t tree_30_is_leaf[15] = {0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1};
static const int8_t tree_30_default_left[15] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_30_N_NODES 15

static const int32_t tree_31_features[13] = {26, 13, 23, -1, -1, 21, -1, 28, 18, -1, -1, -1, -1};
static const float tree_31_thresholds[13] = {0.2085f, 42.76f, 967.0f, 0.0f, 0.0f, 27.37f, 0.0f, 0.3124f, 0.01906f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_31_left[13] = {1, 3, 5, -1, -1, 7, -1, 9, 11, -1, -1, -1, -1};
static const int32_t tree_31_right[13] = {2, 4, 6, -1, -1, 8, -1, 10, 12, -1, -1, -1, -1};
static const float tree_31_leaves[13] = {0.0f, 0.0f, 0.0f, 0.08827737f, -0.020509172f, 0.0f, -0.0895445f, 0.0f, 0.0f, 0.076495774f, -0.0046003014f, -0.083443366f, 0.00990099f};
static const int8_t tree_31_is_leaf[13] = {0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1};
static const int8_t tree_31_default_left[13] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_31_N_NODES 13

static const int32_t tree_32_features[15] = {7, 23, 21, 25, 1, -1, -1, -1, -1, 26, 5, -1, -1, -1, -1};
static const float tree_32_thresholds[15] = {0.05596f, 653.6f, 23.84f, 0.08298f, 19.63f, 0.0f, 0.0f, 0.0f, 0.0f, 0.2177f, 0.07175f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_32_left[15] = {1, 3, 5, 7, 9, -1, -1, -1, -1, 11, 13, -1, -1, -1, -1};
static const int32_t tree_32_right[15] = {2, 4, 6, 8, 10, -1, -1, -1, -1, 12, 14, -1, -1, -1, -1};
static const float tree_32_leaves[15] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0030663149f, -0.08500611f, 0.013680398f, 0.08545404f, 0.0f, 0.0f, 0.07005493f, 0.010240046f, -0.09584576f, 0.011037354f};
static const int8_t tree_32_is_leaf[15] = {0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1};
static const int8_t tree_32_default_left[15] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_32_N_NODES 15

static const int32_t tree_33_features[15] = {27, 13, 16, 21, 24, -1, -1, 28, 1, -1, -1, -1, -1, -1, -1};
static const float tree_33_thresholds[15] = {0.1515f, 34.44f, 0.0643f, 30.12f, 0.1048f, 0.0f, 0.0f, 0.3157f, 23.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_33_left[15] = {1, 3, 5, 7, 9, -1, -1, 11, 13, -1, -1, -1, -1, -1, -1};
static const int32_t tree_33_right[15] = {2, 4, 6, 8, 10, -1, -1, 12, 14, -1, -1, -1, -1, -1, -1};
static const float tree_33_leaves[15] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -0.08403226f, -0.016071655f, 0.0f, 0.0f, 0.023642538f, -0.05921352f, 0.0874058f, 0.0071613104f, -0.05479395f, 0.054152425f};
static const int8_t tree_33_is_leaf[15] = {0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1};
static const int8_t tree_33_default_left[15] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_33_N_NODES 15

static const int32_t tree_34_features[15] = {23, 24, 6, 9, 22, -1, -1, -1, 15, -1, 21, -1, -1, -1, -1};
static const float tree_34_thresholds[15] = {876.5f, 0.138f, 0.0716f, 0.05592f, 87.16f, 0.0f, 0.0f, 0.0f, 0.0103f, 0.0f, 27.21f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_34_left[15] = {1, 3, 5, 7, 9, -1, -1, -1, 11, -1, 13, -1, -1, -1, -1};
static const int32_t tree_34_right[15] = {2, 4, 6, 8, 10, -1, -1, -1, 12, -1, 14, -1, -1, -1, -1};
static const float tree_34_leaves[15] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0065756426f, -0.08556675f, -0.023703061f, 0.0f, 0.054688938f, 0.0f, 0.015059801f, 0.0869787f, 0.010804945f, -0.08845304f};
static const int8_t tree_34_is_leaf[15] = {0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1};
static const int8_t tree_34_default_left[15] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_34_N_NODES 15

static const int32_t tree_35_features[11] = {26, 13, 23, -1, -1, 21, -1, -1, 4, -1, -1};
static const float tree_35_thresholds[11] = {0.2085f, 42.76f, 967.0f, 0.0f, 0.0f, 25.58f, 0.0f, 0.0f, 0.08946f, 0.0f, 0.0f};
static const int32_t tree_35_left[11] = {1, 3, 5, -1, -1, 7, -1, -1, 9, -1, -1};
static const int32_t tree_35_right[11] = {2, 4, 6, -1, -1, 8, -1, -1, 10, -1, -1};
static const float tree_35_leaves[11] = {0.0f, 0.0f, 0.0f, 0.084002174f, -0.020074738f, 0.0f, -0.084595054f, 0.062452476f, 0.0f, 0.014374527f, -0.0667784f};
static const int8_t tree_35_is_leaf[11] = {0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1};
static const int8_t tree_35_default_left[11] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_35_N_NODES 11

static const int32_t tree_36_features[13] = {27, 1, -1, 23, 23, 11, -1, -1, 5, -1, -1, -1, -1};
static const float tree_36_thresholds[13] = {0.1583f, 20.2f, 0.0f, 967.0f, 653.6f, 1.743f, 0.0f, 0.0f, 0.07175f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_36_left[13] = {1, 3, -1, 5, 7, 9, -1, -1, 11, -1, -1, -1, -1};
static const int32_t tree_36_right[13] = {2, 4, -1, 6, 8, 10, -1, -1, 12, -1, -1, -1, -1};
static const float tree_36_leaves[13] = {0.0f, 0.0f, -0.07750317f, 0.0f, 0.0f, 0.0f, -0.010769021f, 0.0521388f, 0.0f, 0.08390564f, 0.010298122f, -0.088786386f, -0.0148885995f};
static const int8_t tree_36_is_leaf[13] = {0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1};
static const int8_t tree_36_default_left[13] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_36_N_NODES 13

static const int32_t tree_37_features[13] = {26, 13, 23, -1, -1, 21, -1, 27, 24, -1, -1, -1, -1};
static const float tree_37_thresholds[13] = {0.2085f, 42.76f, 967.0f, 0.0f, 0.0f, 27.37f, 0.0f, 0.1465f, 0.1407f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_37_left[13] = {1, 3, 5, -1, -1, 7, -1, 9, 11, -1, -1, -1, -1};
static const int32_t tree_37_right[13] = {2, 4, 6, -1, -1, 8, -1, 10, 12, -1, -1, -1, -1};
static const float tree_37_leaves[13] = {0.0f, 0.0f, 0.0f, 0.08161135f, -0.017983122f, 0.0f, -0.08192635f, 0.0f, 0.0f, 0.06779568f, 0.00137445f, 0.0052938657f, -0.07843458f};
static const int8_t tree_37_is_leaf[13] = {0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1};
static const int8_t tree_37_default_left[13] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_37_N_NODES 13

static const int32_t tree_38_features[13] = {27, 1, -1, 23, 23, 11, -1, -1, 5, -1, -1, -1, -1};
static const float tree_38_thresholds[13] = {0.1583f, 20.2f, 0.0f, 967.0f, 653.6f, 1.687f, 0.0f, 0.0f, 0.06678f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_38_left[13] = {1, 3, -1, 5, 7, 9, -1, -1, 11, -1, -1, -1, -1};
static const int32_t tree_38_right[13] = {2, 4, -1, 6, 8, 10, -1, -1, 12, -1, -1, -1, -1};
static const float tree_38_leaves[13] = {0.0f, 0.0f, -0.074024126f, 0.0f, 0.0f, 0.0f, -0.007790019f, 0.049619757f, 0.0f, 0.08082319f, 0.010320616f, -0.08743988f, -0.014930911f};
static const int8_t tree_38_is_leaf[13] = {0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1};
static const int8_t tree_38_default_left[13] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_38_N_NODES 13

static const int32_t tree_39_features[11] = {26, 13, 22, -1, -1, -1, 21, -1, 4, -1, -1};
static const float tree_39_thresholds[11] = {0.2085f, 42.76f, 91.63f, 0.0f, 0.0f, 0.0f, 23.84f, 0.0f, 0.08946f, 0.0f, 0.0f};
static const int32_t tree_39_left[11] = {1, 3, 5, -1, -1, -1, 7, -1, 9, -1, -1};
static const int32_t tree_39_right[11] = {2, 4, 6, -1, -1, -1, 8, -1, 10, -1, -1};
static const float tree_39_leaves[11] = {0.0f, 0.0f, 0.0f, 0.07918001f, -0.016092634f, 0.042617723f, 0.0f, 0.0043616276f, 0.0f, -0.014993991f, -0.0826493f};
static const int8_t tree_39_is_leaf[11] = {0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1};
static const int8_t tree_39_default_left[11] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_39_N_NODES 11

static const int32_t tree_40_features[13] = {7, 15, 21, 16, 28, -1, -1, -1, -1, 7, -1, -1, -1};
static const float tree_40_thresholds[13] = {0.05596f, 0.01203f, 23.84f, 0.01272f, 0.3215f, 0.0f, 0.0f, 0.0f, 0.0f, 0.04335f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_40_left[13] = {1, 3, 5, 7, 9, -1, -1, -1, -1, 11, -1, -1, -1};
static const int32_t tree_40_right[13] = {2, 4, 6, 8, 10, -1, -1, -1, -1, 12, -1, -1, -1};
static const float tree_40_leaves[13] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0039364034f, -0.07472467f, 0.042515144f, -0.07590931f, 0.0f, -0.015847277f, 0.08367184f, 0.021696076f};
static const int8_t tree_40_is_leaf[13] = {0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1};
static const int8_t tree_40_default_left[13] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_40_N_NODES 13

static const int32_t tree_41_features[13] = {26, 13, 23, -1, -1, 21, -1, 7, 24, -1, -1, -1, -1};
static const float tree_41_thresholds[13] = {0.2085f, 42.76f, 967.0f, 0.0f, 0.0f, 27.37f, 0.0f, 0.0598f, 0.1407f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_41_left[13] = {1, 3, 5, -1, -1, 7, -1, 9, 11, -1, -1, -1, -1};
static const int32_t tree_41_right[13] = {2, 4, 6, -1, -1, 8, -1, 10, 12, -1, -1, -1, -1};
static const float tree_41_leaves[13] = {0.0f, 0.0f, 0.0f, 0.07679894f, -0.01568208f, 0.0f, -0.07736901f, 0.0f, 0.0f, 0.059943337f, 0.010422484f, 0.004859548f, -0.07134079f};
static const int8_t tree_41_is_leaf[13] = {0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1};
static const int8_t tree_41_default_left[13] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_41_N_NODES 13

static const int32_t tree_42_features[13] = {20, 7, 1, -1, -1, 26, 4, -1, 23, -1, -1, -1, -1};
static const float tree_42_thresholds[13] = {14.49f, 0.0351f, 19.77f, 0.0f, 0.0f, 0.2241f, 0.08946f, 0.0f, 967.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_42_left[13] = {1, 3, 5, -1, -1, 7, 9, -1, 11, -1, -1, -1, -1};
static const int32_t tree_42_right[13] = {2, 4, 6, -1, -1, 8, 10, -1, 12, -1, -1, -1, -1};
static const float tree_42_leaves[13] = {0.0f, 0.0f, 0.0f, 0.07296418f, -0.00034135926f, 0.0f, 0.0f, 0.06231602f, 0.0f, -0.014040093f, -0.08089523f, 0.029620338f, -0.0591632f};
static const int8_t tree_42_is_leaf[13] = {0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1};
static const int8_t tree_42_default_left[13] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_42_N_NODES 13

static const int32_t tree_43_features[11] = {27, 15, -1, 7, 23, -1, -1, 27, -1, -1, -1};
static const float tree_43_thresholds[11] = {0.1583f, 0.01203f, 0.0f, 0.02657f, 876.5f, 0.0f, 0.0f, 0.1357f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_43_left[11] = {1, 3, -1, 5, 7, -1, -1, 9, -1, -1, -1};
static const int32_t tree_43_right[11] = {2, 4, -1, 6, 8, -1, -1, 10, -1, -1, -1};
static const float tree_43_leaves[11] = {0.0f, 0.0f, -0.0667808f, 0.0f, 0.0f, 0.02013406f, -0.064048596f, 0.0f, -0.02121566f, 0.081402555f, 0.012489046f};
static const int8_t tree_43_is_leaf[11] = {0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1};
static const int8_t tree_43_default_left[11] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_43_N_NODES 11

static const int32_t tree_44_features[11] = {26, 13, 20, -1, -1, -1, 24, 9, -1, -1, -1};
static const float tree_44_thresholds[11] = {0.2085f, 42.76f, 14.49f, 0.0f, 0.0f, 0.0f, 0.1353f, 0.05669f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_44_left[11] = {1, 3, 5, -1, -1, -1, 7, 9, -1, -1, -1};
static const int32_t tree_44_right[11] = {2, 4, 6, -1, -1, -1, 8, 10, -1, -1, -1};
static const float tree_44_leaves[11] = {0.0f, 0.0f, 0.0f, 0.07324088f, -0.014504922f, 0.031914916f, 0.0f, 0.0f, -0.07058244f, -0.056748796f, 0.025665153f};
static const int8_t tree_44_is_leaf[11] = {0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1};
static const int8_t tree_44_default_left[11] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_44_N_NODES 11

static const int32_t tree_45_features[11] = {22, 15, -1, 7, 28, -1, -1, 18, -1, -1, -1};
static const float tree_45_thresholds[11] = {120.4f, 0.01203f, 0.0f, 0.02657f, 0.3215f, 0.0f, 0.0f, 0.01487f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_45_left[11] = {1, 3, -1, 5, 7, -1, -1, 9, -1, -1, -1};
static const int32_t tree_45_right[11] = {2, 4, -1, 6, 8, -1, -1, 10, -1, -1, -1};
static const float tree_45_leaves[11] = {0.0f, 0.0f, -0.06264489f, 0.0f, 0.0f, 0.017575823f, -0.06571665f, 0.0f, -0.032564048f, 0.008652162f, 0.073363215f};
static const int8_t tree_45_is_leaf[11] = {0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1};
static const int8_t tree_45_default_left[11] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_45_N_NODES 11

static const int32_t tree_46_features[13] = {26, 13, 23, -1, -1, 21, -1, 7, 15, -1, -1, -1, -1};
static const float tree_46_thresholds[13] = {0.2085f, 42.76f, 967.0f, 0.0f, 0.0f, 27.37f, 0.0f, 0.05596f, 0.01797f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_46_left[13] = {1, 3, 5, -1, -1, 7, -1, 9, 11, -1, -1, -1, -1};
static const int32_t tree_46_right[13] = {2, 4, 6, -1, -1, 8, -1, 10, 12, -1, -1, -1, -1};
static const float tree_46_leaves[13] = {0.0f, 0.0f, 0.0f, 0.07089062f, -0.013101207f, 0.0f, -0.07076561f, 0.0f, 0.0f, 0.055604935f, 0.01176672f, -0.06705922f, -0.0023781334f};
static const int8_t tree_46_is_leaf[13] = {0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1};
static const int8_t tree_46_default_left[13] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_46_N_NODES 13

static const int32_t tree_47_features[11] = {27, 1, -1, 8, 23, -1, -1, -1, 5, -1, -1};
static const float tree_47_thresholds[11] = {0.1583f, 20.2f, 0.0f, 0.1628f, 653.6f, 0.0f, 0.0f, 0.0f, 0.07175f, 0.0f, 0.0f};
static const int32_t tree_47_left[11] = {1, 3, -1, 5, 7, -1, -1, -1, 9, -1, -1};
static const int32_t tree_47_right[11] = {2, 4, -1, 6, 8, -1, -1, -1, 10, -1, -1};
static const float tree_47_leaves[11] = {0.0f, 0.0f, -0.061529715f, 0.0f, 0.0f, 0.007354853f, 0.06609381f, 0.036786404f, 0.0f, -0.071460165f, -0.007967306f};
static const int8_t tree_47_is_leaf[11] = {0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1};
static const int8_t tree_47_default_left[11] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_47_N_NODES 11

static const int32_t tree_48_features[11] = {7, 15, 21, 1, 23, -1, -1, -1, -1, -1, -1};
static const float tree_48_thresholds[11] = {0.0539f, 0.01203f, 23.84f, 21.53f, 876.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const int32_t tree_48_left[11] = {1, 3, 5, 7, 9, -1, -1, -1, -1, -1, -1};
static const int32_t tree_48_right[11] = {2, 4, 6, 8, 10, -1, -1, -1, -1, -1, -1};
static const float tree_48_leaves[11] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.007882608f, -0.0662046f, 0.010044162f, -0.056575734f, 0.067719094f, -0.0005049822f};
static const int8_t tree_48_is_leaf[11] = {0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1};
static const int8_t tree_48_default_left[11] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_48_N_NODES 11

static const int32_t tree_49_features[11] = {26, 13, 20, -1, -1, -1, 21, -1, 4, -1, -1};
static const float tree_49_thresholds[11] = {0.2085f, 42.76f, 14.49f, 0.0f, 0.0f, 0.0f, 23.84f, 0.0f, 0.08946f, 0.0f, 0.0f};
static const int32_t tree_49_left[11] = {1, 3, 5, -1, -1, -1, 7, -1, 9, -1, -1};
static const int32_t tree_49_right[11] = {2, 4, 6, -1, -1, -1, 8, -1, 10, -1, -1};
static const float tree_49_leaves[11] = {0.0f, 0.0f, 0.0f, 0.067910604f, -0.012542396f, 0.027526904f, 0.0f, 0.00012298634f, 0.0f, -0.0137868f, -0.06964765f};
static const int8_t tree_49_is_leaf[11] = {0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1};
static const int8_t tree_49_default_left[11] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define TREE_49_N_NODES 11

static const float TIMBER_BASE_SCORE = 0.5260931877f;

