"""Intel FPGA HLS emitter — generates HLS C++ for Intel (Quartus) FPGAs."""

from __future__ import annotations

from timber.codegen.c99 import TargetSpec
from timber.ir.model import TimberIR, TreeEnsembleStage

from timber.accel.accel.hls.base import HLSEmitterBase


class IntelFPGAEmitter(HLSEmitterBase):
    """Emit Intel HLS Compiler C++ with ihc::stream interfaces and Intel pragmas."""

    def __init__(self, target: TargetSpec, hls_config: dict):
        super().__init__(target, hls_config)
        self.clock_mhz = hls_config.get("clock_mhz", 200)
        self.device_family = hls_config.get("device_family", "Arria 10")
        self.device_part = hls_config.get("part", "10AX115S2F45I1SG")

    def vendor_name(self) -> str:
        return "intel"

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _flatten_trees(ir_or_stage):
        """Flatten all trees in a stage into contiguous arrays.

        Accepts either a TimberIR (extracts first TreeEnsembleStage) or
        a TreeEnsembleStage directly.

        Returns dict with keys: features, thresholds, left, right, is_leaf,
        leaf_values, offsets.
        """
        if isinstance(ir_or_stage, TimberIR):
            stage = None
            for s in ir_or_stage.pipeline:
                if isinstance(s, TreeEnsembleStage):
                    stage = s
                    break
            if stage is None:
                raise ValueError("TimberIR contains no TreeEnsembleStage")
        else:
            stage = ir_or_stage
        feat, thresh, left, right, is_leaf, leaf_val = [], [], [], [], [], []
        offsets = []
        for tree in stage.trees:
            offsets.append(len(feat))
            for node in tree.nodes:
                feat.append(node.feature_index if not node.is_leaf else -1)
                thresh.append(node.threshold if not node.is_leaf else 0.0)
                left.append(node.left_child if not node.is_leaf else -1)
                right.append(node.right_child if not node.is_leaf else -1)
                is_leaf.append(1 if node.is_leaf else 0)
                leaf_val.append(node.leaf_value if node.is_leaf else 0.0)
        offsets.append(len(feat))
        return {
            "features": feat,
            "thresholds": thresh,
            "left": left,
            "right": right,
            "is_leaf": is_leaf,
            "leaf_values": leaf_val,
            "offsets": offsets,
        }

    @staticmethod
    def _cpp_array(ctype: str, name: str, values) -> str:
        body = ", ".join(str(v) + ("f" if ctype == "float" else "") for v in values)
        return f"static const {ctype} {name}[] = {{{body}}};"

    # ------------------------------------------------------------------
    # HLS source
    # ------------------------------------------------------------------

    def emit_hls_source(self, ir: TimberIR) -> str:
        if not ir.pipeline:
            raise ValueError("IR pipeline is empty")
        stage: TreeEnsembleStage = ir.pipeline[0]
        n_features = stage.n_features
        n_classes = max(stage.n_classes, 1)
        n_trees = len(stage.trees)
        base_score = stage.base_score
        max_depth = max(t.max_depth for t in stage.trees)

        flat = self._flatten_trees(stage)
        feat, thresh = flat["features"], flat["thresholds"]
        left, right = flat["left"], flat["right"]
        is_leaf, leaf_val, offsets = flat["is_leaf"], flat["leaf_values"], flat["offsets"]
        total_nodes = len(feat)

        lines = [
            "/* Auto-generated by TimberAccelerate — Intel FPGA HLS backend */",
            "#include \"HLS/hls.h\"",
            "#include \"HLS/stdio.h\"",
            "#include <string.h>",
            "",
            f"#define N_TREES       {n_trees}",
            f"#define N_FEATURES    {n_features}",
            f"#define N_CLASSES     {n_classes}",
            f"#define TOTAL_NODES   {total_nodes}",
            f"#define MAX_DEPTH     {max_depth}",
            f"#define BASE_SCORE    {base_score}f",
            "",
            "/* ---- Flat tree data ---- */",
            self._cpp_array("int", "tree_feature_idx", feat),
            self._cpp_array("float", "tree_threshold", thresh),
            self._cpp_array("int", "tree_left", left),
            self._cpp_array("int", "tree_right", right),
            self._cpp_array("int", "tree_is_leaf", is_leaf),
            self._cpp_array("float", "tree_leaf_value", leaf_val),
            self._cpp_array("int", "tree_offsets", offsets),
            "",
            "/* --------------------------------------------------",
            " * Streaming interfaces for input and output.",
            " * -------------------------------------------------- */",
            "using FeaturePacket = struct {",
            "    float data[N_FEATURES];",
            "};",
            "",
            "using ResultPacket = struct {",
            "    float data[N_CLASSES];",
            "};",
            "",
            "ihc::stream_in<FeaturePacket>  feature_stream;",
            "ihc::stream_out<ResultPacket>  result_stream;",
            "",
            "/* --------------------------------------------------",
            " * Single-sample inference (inlined into component).",
            " * -------------------------------------------------- */",
            "static void infer_one(",
            "    const float features[N_FEATURES],",
            "    float result[N_CLASSES])",
            "{",
            "    for (int c = 0; c < N_CLASSES; ++c)",
            "        result[c] = BASE_SCORE;",
            "",
            "    for (int t = 0; t < N_TREES; ++t) {",
            "        int idx = tree_offsets[t];",
            "",
            "        #pragma unroll",
            "        for (int d = 0; d < MAX_DEPTH; ++d) {",
            "            if (tree_is_leaf[idx]) break;",
            "            int fid = tree_feature_idx[idx];",
            "            idx = (features[fid] <= tree_threshold[idx])",
            "                  ? tree_left[idx] + tree_offsets[t]",
            "                  : tree_right[idx] + tree_offsets[t];",
            "        }",
            "",
        ]

        if n_classes <= 1:
            lines.append("        result[0] += tree_leaf_value[idx];")
        else:
            lines += [
                "        int cls = t % N_CLASSES;",
                "        result[cls] += tree_leaf_value[idx];",
            ]

        lines += [
            "    }",
            "}",
            "",
            "/* --------------------------------------------------",
            " * HLS component: streaming tree-ensemble inference.",
            " *",
            " * Reads FeaturePackets from feature_stream and writes",
            " * ResultPackets to result_stream.  The hls_register",
            " * attribute maps local arrays to register storage for",
            " * minimum latency.",
            " * -------------------------------------------------- */",
            "hls_avalon_streaming_component",
            "void timber_infer_component(",
            "    ihc::stream_in<FeaturePacket>&  in,",
            "    ihc::stream_out<ResultPacket>& out,",
            "    int n_samples)",
            "{",
            "    for (int s = 0; s < n_samples; ++s) {",
            "        FeaturePacket pkt = in.read();",
            "",
            "        hls_register float features[N_FEATURES];",
            "        for (int i = 0; i < N_FEATURES; ++i)",
            "            features[i] = pkt.data[i];",
            "",
            "        hls_register float result[N_CLASSES];",
            "        infer_one(features, result);",
            "",
            "        ResultPacket rpkt;",
            "        for (int c = 0; c < N_CLASSES; ++c)",
            "            rpkt.data[c] = result[c];",
            "        out.write(rpkt);",
            "    }",
            "}",
            "",
            "/* --------------------------------------------------",
            " * Memory-mapped variant for Avalon MM interface.",
            " *",
            " * Reads/writes from DDR via Avalon master ports.",
            " * -------------------------------------------------- */",
            "hls_avalon_slave_component",
            "void timber_infer_hls(",
            "    hls_avalon_slave_memory_argument(N_FEATURES * 4096 * sizeof(float))",
            "        const float* input,",
            "    hls_avalon_slave_memory_argument(N_CLASSES * 4096 * sizeof(float))",
            "        float* output,",
            "    int n_samples)",
            "{",
            "    hls_register float features[N_FEATURES];",
            "    hls_register float result[N_CLASSES];",
            "",
            "    /* Use hls_bankbits to control bank selection for tree arrays. */",
            f"    hls_bankbits(0, 1) static const int local_feature_idx[TOTAL_NODES]",
            "        __attribute__((section(\".tree_data\")));",
            "",
            "    for (int s = 0; s < n_samples; ++s) {",
            "        /* Burst-read features. */",
            "        for (int i = 0; i < N_FEATURES; ++i)",
            "            features[i] = input[s * N_FEATURES + i];",
            "",
            "        infer_one(features, result);",
            "",
            "        /* Burst-write results. */",
            "        for (int c = 0; c < N_CLASSES; ++c)",
            "            output[s * N_CLASSES + c] = result[c];",
            "    }",
            "}",
            "",
        ]

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Testbench
    # ------------------------------------------------------------------

    def emit_testbench(self, ir: TimberIR) -> str:
        stage = ir.pipeline[0]
        n_features = stage.n_features
        n_classes = max(stage.n_classes, 1)

        return "\n".join([
            "/* Auto-generated testbench — Intel FPGA HLS */",
            "#include \"HLS/hls.h\"",
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "",
            f"#define N_FEATURES {n_features}",
            f"#define N_CLASSES  {n_classes}",
            "",
            "void timber_infer_hls(const float*, float*, int);",
            "",
            "int main() {",
            "    const int n_samples = 4;",
            "    float input[n_samples * N_FEATURES];",
            "    float output[n_samples * N_CLASSES];",
            "",
            "    /* Fill with deterministic test data. */",
            "    for (int i = 0; i < n_samples * N_FEATURES; ++i)",
            "        input[i] = (float)(i % 7) * 0.1f;",
            "",
            "    timber_infer_hls(input, output, n_samples);",
            "",
            "    for (int s = 0; s < n_samples; ++s) {",
            "        printf(\"sample %d:\", s);",
            "        for (int c = 0; c < N_CLASSES; ++c)",
            "            printf(\" %.6f\", output[s * N_CLASSES + c]);",
            "        printf(\"\\n\");",
            "    }",
            "",
            "    printf(\"PASSED\\n\");",
            "    return 0;",
            "}",
            "",
        ])

    # ------------------------------------------------------------------
    # TCL script for Intel HLS compiler
    # ------------------------------------------------------------------

    def emit_tcl_script(self, ir: TimberIR) -> str:
        return "\n".join([
            "# Auto-generated Intel HLS Compiler project script",
            "# Usage: i++ -march=<device> model.cpp -o timber_hls",
            "# Or source this TCL from Quartus Prime Pro.",
            "",
            "package require -exact qsys 16.0",
            "",
            "# Create project",
            "create_system timber_hls",
            f"set_project_property DEVICE_FAMILY \"{self.device_family}\"",
            f"set_project_property DEVICE {{{self.device_part}}}",
            "",
            "# Add HLS component",
            "add_instance timber_infer_hls hls_component",
            "set_instance_property timber_infer_hls SOURCE_FILES model.cpp",
            "set_instance_property timber_infer_hls TOP_FUNCTION timber_infer_hls",
            "",
            "# Clock",
            f"set_instance_property timber_infer_hls CLOCK_RATE {self.clock_mhz}000000",
            "",
            "# Synthesis flow",
            "# i++ --simulator none -march=\"Arria 10\" model.cpp -o timber_hls",
            "",
            "# Emulation (x86 functional test)",
            "# i++ -march=x86-64 model.cpp testbench.cpp -o timber_emu",
            "# ./timber_emu",
            "",
            "# FPGA synthesis",
            f"# i++ -march=\"{self.device_family}\" -clock={self.clock_mhz}MHz \\",
            "#     model.cpp -o timber_hls",
            "",
            "save_system timber_hls.qsys",
            "",
        ])
