"""Xilinx Vitis HLS emitter — generates synthesisable C++ for Xilinx FPGAs."""

from __future__ import annotations

from timber.accel.accel.hls.base import HLSEmitterBase
from timber.codegen.c99 import TargetSpec
from timber.ir.model import TimberIR, TreeEnsembleStage


class XilinxVitisEmitter(HLSEmitterBase):
    """Emit Vitis HLS C++ with AXI-Lite control, pipelining, and array partitioning."""

    def __init__(self, target: TargetSpec, hls_config: dict):
        super().__init__(target, hls_config)
        self.clock_mhz = hls_config.get("clock_mhz", 200)
        self.part = hls_config.get("part", "xcu250-figd2104-2L-e")
        self.pipeline_ii = hls_config.get("pipeline_ii", 1)
        self.unroll_trees = hls_config.get("unroll_trees", False)

    def vendor_name(self) -> str:
        return "xilinx"

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _flatten_trees(ir_or_stage):
        """Flatten all trees in a stage into contiguous arrays.

        Accepts either a TimberIR (extracts first TreeEnsembleStage) or
        a TreeEnsembleStage directly.

        Returns dict with keys: features, thresholds, left, right, is_leaf,
        leaf_values, offsets.
        """
        if isinstance(ir_or_stage, TimberIR):
            stage = None
            for s in ir_or_stage.pipeline:
                if isinstance(s, TreeEnsembleStage):
                    stage = s
                    break
            if stage is None:
                raise ValueError("TimberIR contains no TreeEnsembleStage")
        else:
            stage = ir_or_stage
        feat, thresh, left, right, is_leaf, leaf_val = [], [], [], [], [], []
        offsets = []
        for tree in stage.trees:
            offsets.append(len(feat))
            for node in tree.nodes:
                feat.append(node.feature_index if not node.is_leaf else -1)
                thresh.append(node.threshold if not node.is_leaf else 0.0)
                left.append(node.left_child if not node.is_leaf else -1)
                right.append(node.right_child if not node.is_leaf else -1)
                is_leaf.append(1 if node.is_leaf else 0)
                leaf_val.append(node.leaf_value if node.is_leaf else 0.0)
        offsets.append(len(feat))
        return {
            "features": feat,
            "thresholds": thresh,
            "left": left,
            "right": right,
            "is_leaf": is_leaf,
            "leaf_values": leaf_val,
            "offsets": offsets,
        }

    @staticmethod
    def _cpp_array(ctype: str, name: str, values) -> str:
        body = ", ".join(str(v) + ("f" if ctype == "float" else "") for v in values)
        return f"static const {ctype} {name}[] = {{{body}}};"

    # ------------------------------------------------------------------
    # HLS source
    # ------------------------------------------------------------------

    def emit_hls_source(self, ir: TimberIR) -> str:
        if not ir.pipeline:
            raise ValueError("IR pipeline is empty")
        stage: TreeEnsembleStage = ir.pipeline[0]
        n_features = stage.n_features
        n_classes = max(stage.n_classes, 1)
        n_trees = len(stage.trees)
        base_score = stage.base_score
        max_depth = max(t.max_depth for t in stage.trees)

        flat = self._flatten_trees(stage)
        feat, thresh = flat["features"], flat["thresholds"]
        left, right = flat["left"], flat["right"]
        is_leaf, leaf_val, offsets = flat["is_leaf"], flat["leaf_values"], flat["offsets"]
        total_nodes = len(feat)

        lines = [
            "/* Auto-generated by TimberAccelerate — Xilinx Vitis HLS backend */",
            "#include <stdint.h>",
            "#include <string.h>",
            "",
            f"#define N_TREES       {n_trees}",
            f"#define N_FEATURES    {n_features}",
            f"#define N_CLASSES     {n_classes}",
            f"#define TOTAL_NODES   {total_nodes}",
            f"#define MAX_DEPTH     {max_depth}",
            f"#define BASE_SCORE    {base_score}f",
            "",
            "/* ---- Flat tree data ---- */",
            self._cpp_array("int", "tree_feature_idx", feat),
            self._cpp_array("float", "tree_threshold", thresh),
            self._cpp_array("int", "tree_left", left),
            self._cpp_array("int", "tree_right", right),
            self._cpp_array("int", "tree_is_leaf", is_leaf),
            self._cpp_array("float", "tree_leaf_value", leaf_val),
            self._cpp_array("int", "tree_offsets", offsets),
            "",
            "/* --------------------------------------------------",
            " * Single-sample inference: traverse all trees.",
            " * -------------------------------------------------- */",
            "static void infer_one(const float features[N_FEATURES],",
            "                      float result[N_CLASSES]) {",
            "#pragma HLS INLINE",
            "",
            "    for (int c = 0; c < N_CLASSES; ++c)",
            "        result[c] = BASE_SCORE;",
            "",
            "    TREE_LOOP:",
            "    for (int t = 0; t < N_TREES; ++t) {",
        ]

        if self.unroll_trees:
            lines.append("#pragma HLS UNROLL")
        else:
            lines.append(f"#pragma HLS PIPELINE II={self.pipeline_ii}")

        lines += [
            "        int idx = tree_offsets[t];",
            "",
            "        DEPTH_LOOP:",
            "        for (int d = 0; d < MAX_DEPTH; ++d) {",
            "#pragma HLS PIPELINE II=1",
            "            if (tree_is_leaf[idx]) break;",
            "            int fid = tree_feature_idx[idx];",
            "            idx = (features[fid] <= tree_threshold[idx])",
            "                  ? tree_left[idx] + tree_offsets[t]",
            "                  : tree_right[idx] + tree_offsets[t];",
            "        }",
            "",
        ]

        if n_classes <= 1:
            lines.append("        result[0] += tree_leaf_value[idx];")
        else:
            lines += [
                "        int cls = t % N_CLASSES;",
                "        result[cls] += tree_leaf_value[idx];",
            ]

        lines += [
            "    }",
            "}",
            "",
            "/* --------------------------------------------------",
            " * Top-level HLS function.",
            " *",
            " * AXI-Lite control; m_axi master ports for data.",
            " * -------------------------------------------------- */",
            "extern \"C\" {",
            "",
            "void timber_infer_hls(",
            "    const float* input,   /* [n_samples, N_FEATURES] */",
            "    float*       output,  /* [n_samples, N_CLASSES]  */",
            "    int          n_samples)",
            "{",
            "#pragma HLS INTERFACE s_axilite port=return",
            "#pragma HLS INTERFACE s_axilite port=n_samples",
            "#pragma HLS INTERFACE m_axi port=input  offset=slave bundle=gmem0 depth=4096",
            "#pragma HLS INTERFACE m_axi port=output offset=slave bundle=gmem1 depth=4096",
            "",
            "    /* Partition the feature and result arrays for parallel access. */",
            "    float features[N_FEATURES];",
            "#pragma HLS ARRAY_PARTITION variable=features complete dim=1",
            "",
            "    float result[N_CLASSES];",
            "#pragma HLS ARRAY_PARTITION variable=result complete dim=1",
            "",
            "    /* Partition tree data for concurrent reads. */",
            "#pragma HLS ARRAY_PARTITION variable=tree_feature_idx cyclic factor=4 dim=1",
            "#pragma HLS ARRAY_PARTITION variable=tree_threshold   cyclic factor=4 dim=1",
            "#pragma HLS ARRAY_PARTITION variable=tree_is_leaf     cyclic factor=4 dim=1",
            "#pragma HLS ARRAY_PARTITION variable=tree_leaf_value  cyclic factor=4 dim=1",
            "",
            "    SAMPLE_LOOP:",
            "    for (int s = 0; s < n_samples; ++s) {",
            "#pragma HLS DATAFLOW",
            "",
            "        /* Burst-read one sample from global memory. */",
            "        memcpy(features, input + s * N_FEATURES,",
            "               N_FEATURES * sizeof(float));",
            "",
            "        /* Infer. */",
            "        infer_one(features, result);",
            "",
            "        /* Burst-write result back. */",
            "        memcpy((void*)(output + s * N_CLASSES), result,",
            "               N_CLASSES * sizeof(float));",
            "    }",
            "}",
            "",
            "} /* extern \"C\" */",
            "",
        ]

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Testbench
    # ------------------------------------------------------------------

    def emit_testbench(self, ir: TimberIR) -> str:
        stage = ir.pipeline[0]
        n_features = stage.n_features
        n_classes = max(stage.n_classes, 1)

        return "\n".join([
            "/* Auto-generated C-sim testbench — Xilinx Vitis HLS */",
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "#include <math.h>",
            "",
            f"#define N_FEATURES {n_features}",
            f"#define N_CLASSES  {n_classes}",
            "",
            "extern \"C\" void timber_infer_hls(const float*, float*, int);",
            "",
            "int main() {",
            "    const int n_samples = 4;",
            "    float input[n_samples * N_FEATURES];",
            "    float output[n_samples * N_CLASSES];",
            "",
            "    /* Fill with deterministic test data. */",
            "    for (int i = 0; i < n_samples * N_FEATURES; ++i)",
            "        input[i] = (float)(i % 7) * 0.1f;",
            "",
            "    timber_infer_hls(input, output, n_samples);",
            "",
            "    /* Print results for manual inspection. */",
            "    for (int s = 0; s < n_samples; ++s) {",
            '        printf("sample %d:", s);',
            "        for (int c = 0; c < N_CLASSES; ++c)",
            '            printf(" %.6f", output[s * N_CLASSES + c]);',
            '        printf("\\n");',
            "    }",
            "",
            '    printf("PASSED\\n");',
            "    return 0;",
            "}",
            "",
        ])

    # ------------------------------------------------------------------
    # TCL synthesis script
    # ------------------------------------------------------------------

    def emit_tcl_script(self, ir: TimberIR) -> str:
        return "\n".join([
            "# Auto-generated Vitis HLS synthesis script",
            "# Usage: vitis_hls -f run_hls.tcl",
            "",
            "open_project timber_hls_prj",
            "set_top timber_infer_hls",
            "",
            "add_files model.c -cflags \"-std=c++14\"",
            "add_files -tb testbench.cpp -cflags \"-std=c++14\"",
            "",
            "open_solution \"solution1\" -flow_target vivado",
            f"set_part {{{self.part}}}",
            f"create_clock -period {{1000.0 / {self.clock_mhz}}}ns -name default",
            "",
            "# C simulation",
            "csim_design",
            "",
            "# Synthesis",
            "csynth_design",
            "",
            "# Co-simulation (optional — comment out to save time)",
            "# cosim_design -tool xsim",
            "",
            "# Export IP (optional)",
            "# export_design -format ip_catalog",
            "",
            "exit",
            "",
        ])
