"""gRPC .proto file generator for TimberAccelerate inference services."""

from __future__ import annotations

import logging
import textwrap
from pathlib import Path

from timber.ir.model import TimberIR

logger = logging.getLogger(__name__)


def generate_proto(
    ir: TimberIR,
    *,
    package: str = "timber_accel",
    java_package: str | None = None,
    output_path: str | Path | None = None,
) -> str:
    """Generate a .proto file for the inference service.

    Parameters
    ----------
    ir:
        The Timber intermediate representation (used for schema info).
    package:
        Protobuf package name.
    java_package:
        Optional Java package for cross-language builds.
    output_path:
        If provided, the .proto text is written to this file.

    Returns
    -------
    str
        The full .proto file content.
    """
    schema = ir.schema
    n_features = schema.n_features
    n_outputs = schema.n_outputs

    java_option = ""
    if java_package:
        java_option = f'option java_package = "{java_package}";\n'

    feature_comments = "\n".join(
        f"    // [{i}] {field.name}"
        for i, field in enumerate(schema.input_fields)
    )
    if not feature_comments:
        feature_comments = "    // (feature schema not available)"

    proto = textwrap.dedent(f"""\
        // Auto-generated by TimberAccelerate — do not edit.
        syntax = "proto3";

        package {package};

        {java_option}
        // -----------------------------------------------------------
        // TimberAccel Inference Service
        // -----------------------------------------------------------

        service TimberAccelInference {{
            // Unary inference call.
            rpc Infer(InferRequest) returns (InferResponse);

            // Bidirectional streaming inference.
            rpc InferStream(stream InferRequest) returns (stream InferResponse);

            // Return static model metadata.
            rpc GetModelInfo(Empty) returns (ModelInfo);
        }}

        // -----------------------------------------------------------
        // Messages
        // -----------------------------------------------------------

        message InferRequest {{
            // Flattened feature vector.
        {feature_comments}
            repeated float features = 1;

            // Optional request identifier for correlation.
            string request_id = 2;
        }}

        message InferResponse {{
            // Model output values (length = {n_outputs}).
            repeated float outputs = 1;

            // Echo back the request identifier.
            string request_id = 2;

            // Server-side latency in microseconds.
            int64 latency_us = 3;

            // Model name that produced this result.
            string model_name = 4;
        }}

        message ModelInfo {{
            string model_name = 1;
            int32 n_features = 2;
            int32 n_outputs = 3;
            int32 max_batch_size = 4;
            string timber_accel_version = 5;
        }}

        message Empty {{}}
    """)

    if output_path is not None:
        p = Path(output_path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(proto)
        logger.info("Proto file written to %s", p)

    return proto
