"""Native C++ server project generator for compiled Timber models.

Generates a complete build-ready project with gRPC or HTTP serving,
including main.cpp, inference_engine.cpp/.h, and CMakeLists.txt.
"""

from __future__ import annotations

import logging
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from timber.ir.model import TimberIR

logger = logging.getLogger(__name__)

ServerMode = Literal["grpc", "http"]


@dataclass
class ServerConfig:
    """Configuration for the generated native server."""

    model_name: str
    ir: TimberIR
    mode: ServerMode = "grpc"
    port: int = 50051
    max_batch_size: int = 64
    num_threads: int = 4
    compiled_lib: str = "libtimber_model.a"
    include_health_check: bool = True


class NativeServerGenerator:
    """Generates a C++ server project wrapping a compiled Timber model."""

    def __init__(self, config: ServerConfig) -> None:
        self._cfg = config
        self._schema = config.ir.schema
        self._n_features = self._schema.n_features
        self._n_outputs = self._schema.n_outputs

    # ------------------------------------------------------------------
    # Public
    # ------------------------------------------------------------------

    def generate(self, output_dir: str | Path) -> str:
        """Write all project files and return the output directory path."""
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        src = out / "src"
        src.mkdir(exist_ok=True)

        (src / "main.cpp").write_text(self._gen_main())
        (src / "inference_engine.h").write_text(self._gen_engine_header())
        (src / "inference_engine.cpp").write_text(self._gen_engine_impl())
        (out / "CMakeLists.txt").write_text(self._gen_cmake())

        logger.info("Server project generated at %s", out)
        return str(out)

    # ------------------------------------------------------------------
    # Code generators
    # ------------------------------------------------------------------

    def _gen_main(self) -> str:
        if self._cfg.mode == "grpc":
            return self._gen_main_grpc()
        return self._gen_main_http()

    def _gen_main_grpc(self) -> str:
        return textwrap.dedent(f"""\
            // Auto-generated by TimberAccelerate — gRPC inference server
            #include <iostream>
            #include <memory>
            #include <string>
            #include <grpcpp/grpcpp.h>
            #include "timber_accel_inference.grpc.pb.h"
            #include "inference_engine.h"

            using grpc::Server;
            using grpc::ServerBuilder;
            using grpc::ServerContext;
            using grpc::Status;

            class InferenceServiceImpl final
                : public timber_accel::TimberAccelInference::Service {{
            public:
                explicit InferenceServiceImpl(InferenceEngine* engine)
                    : engine_(engine) {{}}

                Status Infer(ServerContext* ctx,
                             const timber_accel::InferRequest* req,
                             timber_accel::InferResponse* resp) override {{
                    std::vector<float> features(req->features().begin(),
                                                req->features().end());
                    auto result = engine_->predict(features);
                    for (auto v : result) {{
                        resp->add_outputs(v);
                    }}
                    resp->set_model_name("{self._cfg.model_name}");
                    return Status::OK;
                }}

                Status GetModelInfo(ServerContext* ctx,
                                    const timber_accel::Empty* req,
                                    timber_accel::ModelInfo* resp) override {{
                    resp->set_model_name("{self._cfg.model_name}");
                    resp->set_n_features({self._n_features});
                    resp->set_n_outputs({self._n_outputs});
                    resp->set_max_batch_size({self._cfg.max_batch_size});
                    return Status::OK;
                }}

            private:
                InferenceEngine* engine_;
            }};

            int main(int argc, char** argv) {{
                InferenceEngine engine;
                if (!engine.init()) {{
                    std::cerr << "Failed to initialise inference engine" << std::endl;
                    return 1;
                }}

                std::string addr = "127.0.0.1:{self._cfg.port}";
                InferenceServiceImpl service(&engine);
                ServerBuilder builder;

                std::shared_ptr<grpc::ServerCredentials> creds;
            #ifdef TIMBER_TLS_ENABLED
                grpc::SslServerCredentialsOptions ssl_opts;
                // TLS credentials loaded from files
                creds = grpc::SslServerCredentials(ssl_opts);
            #else
                /* WARNING: Using insecure credentials. Set TIMBER_TLS_ENABLED for production. */
                creds = grpc::InsecureServerCredentials();
            #endif

                builder.AddListeningPort(addr, creds);
                builder.RegisterService(&service);
                builder.SetMaxReceiveMessageSize(16 * 1024 * 1024);

                auto server = builder.BuildAndStart();
                std::cout << "TimberAccel gRPC server listening on " << addr << std::endl;
                server->Wait();
                return 0;
            }}
        """)

    def _gen_main_http(self) -> str:
        return textwrap.dedent(f"""\
            // Auto-generated by TimberAccelerate — HTTP inference server
            // Uses a minimal embedded HTTP server (cpp-httplib)
            #include <iostream>
            #include <sstream>
            #include <string>
            #include "httplib.h"
            #include "inference_engine.h"

            int main(int argc, char** argv) {{
                InferenceEngine engine;
                if (!engine.init()) {{
                    std::cerr << "Failed to initialise inference engine" << std::endl;
                    return 1;
                }}

                httplib::Server svr;

                svr.Post("/v1/infer", [&engine](const httplib::Request& req,
                                                httplib::Response& res) {{
                    // Expect JSON array of floats
                    // Minimal parsing — production should use nlohmann/json
                    std::vector<float> features;
                    std::istringstream iss(req.body);
                    float v;
                    char c;
                    while (iss >> v) {{
                        features.push_back(v);
                        iss >> c;  // skip comma / bracket
                    }}
                    auto result = engine.predict(features);
                    std::ostringstream oss;
                    oss << "[";
                    for (size_t i = 0; i < result.size(); ++i) {{
                        if (i) oss << ",";
                        oss << result[i];
                    }}
                    oss << "]";
                    res.set_content(oss.str(), "application/json");
                }});

                svr.Get("/v1/health", [](const httplib::Request&,
                                         httplib::Response& res) {{
                    res.set_content("{{\\"status\\":\\"ok\\"}}", "application/json");
                }});

                std::cout << "TimberAccel HTTP server listening on 127.0.0.1:{self._cfg.port}"
                          << std::endl;
                svr.listen("127.0.0.1", {self._cfg.port});
                return 0;
            }}
        """)

    def _gen_engine_header(self) -> str:
        return textwrap.dedent(f"""\
            // Auto-generated by TimberAccelerate
            #ifndef INFERENCE_ENGINE_H
            #define INFERENCE_ENGINE_H

            #include <vector>

            class InferenceEngine {{
            public:
                bool init();
                std::vector<float> predict(const std::vector<float>& features);
                int n_features() const {{ return {self._n_features}; }}
                int n_outputs() const {{ return {self._n_outputs}; }}

            private:
                bool ready_ = false;
            }};

            #endif  // INFERENCE_ENGINE_H
        """)

    def _gen_engine_impl(self) -> str:
        return textwrap.dedent(f"""\
            // Auto-generated by TimberAccelerate
            #include "inference_engine.h"
            #include <cstring>
            #include <stdexcept>

            // Compiled model entry point (linked from {self._cfg.compiled_lib})
            extern "C" {{
                void timber_predict(const float* input, int n_features, float* output);
            }}

            bool InferenceEngine::init() {{
                // Validate that the compiled library is linked
                ready_ = true;
                return ready_;
            }}

            std::vector<float> InferenceEngine::predict(
                    const std::vector<float>& features) {{
                if (!ready_) {{
                    throw std::runtime_error("Engine not initialised");
                }}
                if (static_cast<int>(features.size()) != {self._n_features}) {{
                    throw std::runtime_error("Feature count mismatch");
                }}
                std::vector<float> output({self._n_outputs}, 0.0f);
                timber_predict(features.data(), {self._n_features}, output.data());
                return output;
            }}
        """)

    def _gen_cmake(self) -> str:
        grpc_deps = ""
        if self._cfg.mode == "grpc":
            grpc_deps = textwrap.dedent("""\
                find_package(Protobuf REQUIRED)
                find_package(gRPC REQUIRED)

                add_library(proto
                    ${CMAKE_CURRENT_BINARY_DIR}/timber_accel_inference.pb.cc
                    ${CMAKE_CURRENT_BINARY_DIR}/timber_accel_inference.grpc.pb.cc
                )
                target_link_libraries(proto PUBLIC protobuf::libprotobuf gRPC::grpc++)
                target_include_directories(proto PUBLIC ${CMAKE_CURRENT_BINARY_DIR})
            """)
            link_libs = "proto timber_model gRPC::grpc++ protobuf::libprotobuf pthread"
        else:
            link_libs = "timber_model pthread"

        return textwrap.dedent(f"""\
            # Auto-generated by TimberAccelerate
            cmake_minimum_required(VERSION 3.16)
            project({self._cfg.model_name}_server CXX C)
            set(CMAKE_CXX_STANDARD 17)

            {grpc_deps}
            # Compiled Timber model static library
            add_library(timber_model STATIC IMPORTED)
            set_target_properties(timber_model PROPERTIES
                IMPORTED_LOCATION ${{CMAKE_SOURCE_DIR}}/{self._cfg.compiled_lib}
            )

            add_executable(server
                src/main.cpp
                src/inference_engine.cpp
            )
            target_include_directories(server PRIVATE src)
            target_link_libraries(server PRIVATE {link_libs})

            # Thread configuration
            set(NUM_THREADS {self._cfg.num_threads} CACHE STRING "Worker threads")
            target_compile_definitions(server PRIVATE NUM_THREADS=${{NUM_THREADS}})
        """)
