"""CUDA emitter — generates .cu kernels for NVIDIA GPUs."""

from __future__ import annotations

from timber.accel.accel.gpu.base import GPUEmitterBase
from timber.codegen.c99 import TargetSpec
from timber.ir.model import TimberIR, TreeEnsembleStage


class CUDAEmitter(GPUEmitterBase):
    """Emit CUDA kernels that map one thread per sample for tree-ensemble inference."""

    def __init__(self, target: TargetSpec, gpu_config: dict):
        super().__init__(target, gpu_config)
        self.block_size = gpu_config.get("block_size", 256)
        self.use_shared = gpu_config.get("use_shared_memory", False)
        self.max_batch = gpu_config.get("max_batch_size", 1 << 20)

    def backend_name(self) -> str:
        return "cuda"

    # ------------------------------------------------------------------
    # Helpers to flatten tree data into parallel arrays
    # ------------------------------------------------------------------

    @staticmethod
    def _flatten_trees(ir_or_stage):
        """Flatten all trees in a stage into contiguous arrays.

        Accepts either a TimberIR (extracts first TreeEnsembleStage) or
        a TreeEnsembleStage directly.

        Returns dict with keys: features, thresholds, left, right, is_leaf,
        leaf_values, offsets.
        """
        if isinstance(ir_or_stage, TimberIR):
            stage = None
            for s in ir_or_stage.pipeline:
                if isinstance(s, TreeEnsembleStage):
                    stage = s
                    break
            if stage is None:
                raise ValueError("TimberIR contains no TreeEnsembleStage")
        else:
            stage = ir_or_stage
        feat, thresh, left, right, is_leaf, leaf_val = [], [], [], [], [], []
        offsets = []
        for tree in stage.trees:
            offsets.append(len(feat))
            for node in tree.nodes:
                feat.append(node.feature_index if not node.is_leaf else -1)
                thresh.append(node.threshold if not node.is_leaf else 0.0)
                left.append(node.left_child if not node.is_leaf else -1)
                right.append(node.right_child if not node.is_leaf else -1)
                is_leaf.append(1 if node.is_leaf else 0)
                leaf_val.append(node.leaf_value if node.is_leaf else 0.0)
        offsets.append(len(feat))  # sentinel
        return {
            "features": feat,
            "thresholds": thresh,
            "left": left,
            "right": right,
            "is_leaf": is_leaf,
            "leaf_values": leaf_val,
            "offsets": offsets,
        }

    @staticmethod
    def _c_array(ctype: str, name: str, values) -> str:
        body = ", ".join(str(v) + ("f" if ctype == "float" else "") for v in values)
        return f"static const {ctype} {name}[] = {{{body}}};"

    # ------------------------------------------------------------------
    # Kernel emission
    # ------------------------------------------------------------------

    def emit_kernel(self, ir: TimberIR) -> str:
        if not ir.pipeline:
            raise ValueError("IR pipeline is empty")
        stage: TreeEnsembleStage = ir.pipeline[0]
        if not isinstance(stage, TreeEnsembleStage):
            raise ValueError("First pipeline stage must be TreeEnsembleStage")
        n_features = stage.n_features
        n_classes = stage.n_classes
        n_trees = len(stage.trees)
        base_score = stage.base_score

        flat = self._flatten_trees(stage)
        feat, thresh = flat["features"], flat["thresholds"]
        left, right = flat["left"], flat["right"]
        is_leaf, leaf_val, offsets = flat["is_leaf"], flat["leaf_values"], flat["offsets"]
        total_nodes = len(feat)

        # CUDA constant memory limit: 64KB
        const_mem_bytes = total_nodes * (4 + 4 + 4 + 4 + 4 + 4) + (n_trees + 1) * 4  # 6 arrays + offsets
        if const_mem_bytes > 65536:
            import warnings
            warnings.warn(
                f"Tree data ({const_mem_bytes} bytes) exceeds CUDA 64KB constant memory limit. "
                f"Consider using global memory instead.",
                stacklevel=2,
            )

        lines = [
            "/* Auto-generated by TimberAccelerate — CUDA backend */",
            '#include "model.h"',
            "#include <cuda_runtime.h>",
            "#include <stdio.h>",
            "",
            f"#define N_TREES       {n_trees}",
            f"#define N_FEATURES    {n_features}",
            f"#define N_CLASSES     {n_classes}",
            f"#define TOTAL_NODES   {total_nodes}",
            f"#define BASE_SCORE    {base_score}f",
            "",
            "/* ---- Flat tree arrays (device constant memory) ---- */",
            "__constant__ int    d_feature_idx[TOTAL_NODES];",
            "__constant__ float  d_threshold[TOTAL_NODES];",
            "__constant__ int    d_left[TOTAL_NODES];",
            "__constant__ int    d_right[TOTAL_NODES];",
            "__constant__ int    d_is_leaf[TOTAL_NODES];",
            "__constant__ float  d_leaf_value[TOTAL_NODES];",
            f"__constant__ int    d_tree_offsets[{n_trees + 1}];",
            "",
            "/* ---- Host-side tree data ---- */",
            self._c_array("int", "h_feature_idx", feat),
            self._c_array("float", "h_threshold", thresh),
            self._c_array("int", "h_left", left),
            self._c_array("int", "h_right", right),
            self._c_array("int", "h_is_leaf", is_leaf),
            self._c_array("float", "h_leaf_value", leaf_val),
            self._c_array("int", "h_tree_offsets", offsets),
            "",
            "/* --------------------------------------------------",
            " * Kernel: one thread per sample.",
            " * Each thread walks every tree and accumulates the",
            " * leaf values into a prediction.",
            " * -------------------------------------------------- */",
            "__global__ void timber_infer_kernel(",
            "    const float* __restrict__ input,   /* [n_samples, N_FEATURES] */",
            "    float*       __restrict__ output,   /* [n_samples, N_CLASSES]  */",
            "    int n_samples)",
            "{",
            "    int sid = blockIdx.x * blockDim.x + threadIdx.x;",
            "    if (sid >= n_samples) return;",
            "",
            "    const float* row = input + sid * N_FEATURES;",
            "",
        ]

        if n_classes <= 1:
            # Regression or binary classification — single accumulator
            lines += [
                "    float acc = BASE_SCORE;",
                "",
                "    for (int t = 0; t < N_TREES; ++t) {",
                "        int idx = d_tree_offsets[t];",
                "        while (!d_is_leaf[idx]) {",
                "            int fid = d_feature_idx[idx];",
                "            idx = (row[fid] <= d_threshold[idx])",
                "                  ? d_left[idx] + d_tree_offsets[t]",
                "                  : d_right[idx] + d_tree_offsets[t];",
                "        }",
                "        acc += d_leaf_value[idx];",
                "    }",
                "",
                "    output[sid] = acc;",
            ]
        else:
            # Multi-class — accumulate per class
            lines += [
                "    float acc[N_CLASSES];",
                "    for (int c = 0; c < N_CLASSES; ++c) acc[c] = BASE_SCORE;",
                "",
                "    for (int t = 0; t < N_TREES; ++t) {",
                "        int cls = t % N_CLASSES;",
                "        int idx = d_tree_offsets[t];",
                "        while (!d_is_leaf[idx]) {",
                "            int fid = d_feature_idx[idx];",
                "            idx = (row[fid] <= d_threshold[idx])",
                "                  ? d_left[idx] + d_tree_offsets[t]",
                "                  : d_right[idx] + d_tree_offsets[t];",
                "        }",
                "        acc[cls] += d_leaf_value[idx];",
                "    }",
                "",
                "    for (int c = 0; c < N_CLASSES; ++c)",
                "        output[sid * N_CLASSES + c] = acc[c];",
            ]

        lines += [
            "}",
            "",
            "/* --------------------------------------------------",
            " * Device-side helpers: copy constant data once.",
            " * -------------------------------------------------- */",
            "#include <pthread.h>",
            "static int _constants_loaded = 0;",
            "static pthread_mutex_t _constants_mutex = PTHREAD_MUTEX_INITIALIZER;",
            "",
            "static void _load_constants(void) {",
            "    pthread_mutex_lock(&_constants_mutex);",
            "    if (_constants_loaded) { pthread_mutex_unlock(&_constants_mutex); return; }",
            "    cudaMemcpyToSymbol(d_feature_idx, h_feature_idx, sizeof(h_feature_idx));",
            "    cudaMemcpyToSymbol(d_threshold,   h_threshold,   sizeof(h_threshold));",
            "    cudaMemcpyToSymbol(d_left,         h_left,         sizeof(h_left));",
            "    cudaMemcpyToSymbol(d_right,        h_right,        sizeof(h_right));",
            "    cudaMemcpyToSymbol(d_is_leaf,      h_is_leaf,      sizeof(h_is_leaf));",
            "    cudaMemcpyToSymbol(d_leaf_value,   h_leaf_value,   sizeof(h_leaf_value));",
            "    cudaMemcpyToSymbol(d_tree_offsets,  h_tree_offsets,  sizeof(h_tree_offsets));",
            "    _constants_loaded = 1;",
            "    pthread_mutex_unlock(&_constants_mutex);",
            "}",
            "",
        ]

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Host code
    # ------------------------------------------------------------------

    def emit_host(self, ir: TimberIR) -> str:
        stage = ir.pipeline[0]
        n_features = stage.n_features
        n_classes = max(stage.n_classes, 1)
        block = self.block_size

        return "\n".join([
            "/* Auto-generated host driver — CUDA backend */",
            '#include "model.h"',
            "#include <cuda_runtime.h>",
            "#include <stdlib.h>",
            "#include <stdio.h>",
            "",
            f"#define BLOCK_SIZE {block}",
            f"#define N_FEATURES {n_features}",
            f"#define N_CLASSES  {n_classes}",
            "",
            "/* Forward declaration of the kernel launcher. */",
            "extern void _load_constants(void);",
            "extern __global__ void timber_infer_kernel(",
            "    const float*, float*, int);",
            "",
            "int timber_predict_gpu(",
            "    const float* h_input,   /* [n_samples, N_FEATURES] */",
            "    float*       h_output,  /* [n_samples, N_CLASSES]  */",
            "    int          n_samples)",
            "{",
            "    _load_constants();",
            "",
            "    if (n_samples <= 0) return -1;",
            "    if ((size_t)n_samples > SIZE_MAX / (N_FEATURES * sizeof(float))) return -2;  /* overflow */",
            "",
            "    size_t in_bytes  = (size_t)n_samples * N_FEATURES * sizeof(float);",
            "    size_t out_bytes = (size_t)n_samples * N_CLASSES  * sizeof(float);",
            "",
            "    float *d_input = NULL, *d_output = NULL;",
            "    cudaError_t err;",
            "",
            '    err = cudaMalloc((void**)&d_input, in_bytes);',
            '    if (err != cudaSuccess) { fprintf(stderr, "cudaMalloc input: %s\\n", cudaGetErrorString(err)); return -1; }',
            "",
            '    err = cudaMalloc((void**)&d_output, out_bytes);',
            '    if (err != cudaSuccess) { cudaFree(d_input); fprintf(stderr, "cudaMalloc output: %s\\n", cudaGetErrorString(err)); return -1; }',
            "",
            "    cudaMemcpy(d_input, h_input, in_bytes, cudaMemcpyHostToDevice);",
            "",
            "    int grid = (n_samples + BLOCK_SIZE - 1) / BLOCK_SIZE;",
            "    timber_infer_kernel<<<grid, BLOCK_SIZE>>>(d_input, d_output, n_samples);",
            "",
            "    err = cudaGetLastError();",
            '    if (err != cudaSuccess) { fprintf(stderr, "kernel launch: %s\\n", cudaGetErrorString(err)); }',
            "",
            "    cudaMemcpy(h_output, d_output, out_bytes, cudaMemcpyDeviceToHost);",
            "",
            "    cudaFree(d_input);",
            "    cudaFree(d_output);",
            "    return 0;",
            "}",
            "",
        ])

    # ------------------------------------------------------------------
    # Build script
    # ------------------------------------------------------------------

    def emit_build_script(self, ir: TimberIR) -> str:
        return "\n".join([
            "cmake_minimum_required(VERSION 3.18)",
            "project(timber_cuda LANGUAGES C CUDA)",
            "",
            "set(CMAKE_CUDA_STANDARD 14)",
            "set(CMAKE_C_STANDARD 11)",
            "",
            "# Auto-detect GPU architecture if not specified",
            "if(NOT DEFINED CMAKE_CUDA_ARCHITECTURES)",
            '    set(CMAKE_CUDA_ARCHITECTURES "native")',
            "endif()",
            "",
            "add_library(timber_model STATIC",
            "    host.c",
            "    kernel.cu",
            "    model_data.c",
            ")",
            "",
            "target_include_directories(timber_model PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})",
            "",
            "# Optional: build a standalone benchmark executable",
            "# add_executable(timber_bench bench.c)",
            "# target_link_libraries(timber_bench PRIVATE timber_model)",
            "",
        ])
