"""Metal emitter — generates .metal compute shaders for Apple GPUs."""

from __future__ import annotations

from timber.accel.accel.gpu.base import GPUEmitterBase
from timber.codegen.c99 import TargetSpec
from timber.ir.model import TimberIR, TreeEnsembleStage


class MetalEmitter(GPUEmitterBase):
    """Emit Metal compute shaders with one thread per sample inference."""

    def __init__(self, target: TargetSpec, gpu_config: dict):
        super().__init__(target, gpu_config)
        self.threads_per_group = gpu_config.get("threads_per_threadgroup", 256)

    def backend_name(self) -> str:
        return "metal"

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _flatten_trees(ir_or_stage):
        """Flatten all trees in a stage into contiguous arrays.

        Accepts either a TimberIR (extracts first TreeEnsembleStage) or
        a TreeEnsembleStage directly.

        Returns dict with keys: features, thresholds, left, right, is_leaf,
        leaf_values, offsets.
        """
        if isinstance(ir_or_stage, TimberIR):
            stage = None
            for s in ir_or_stage.pipeline:
                if isinstance(s, TreeEnsembleStage):
                    stage = s
                    break
            if stage is None:
                raise ValueError("TimberIR contains no TreeEnsembleStage")
        else:
            stage = ir_or_stage
        feat, thresh, left, right, is_leaf, leaf_val = [], [], [], [], [], []
        offsets = []
        for tree in stage.trees:
            offsets.append(len(feat))
            for node in tree.nodes:
                feat.append(node.feature_index if not node.is_leaf else -1)
                thresh.append(node.threshold if not node.is_leaf else 0.0)
                left.append(node.left_child if not node.is_leaf else -1)
                right.append(node.right_child if not node.is_leaf else -1)
                is_leaf.append(1 if node.is_leaf else 0)
                leaf_val.append(node.leaf_value if node.is_leaf else 0.0)
        offsets.append(len(feat))
        return {
            "features": feat,
            "thresholds": thresh,
            "left": left,
            "right": right,
            "is_leaf": is_leaf,
            "leaf_values": leaf_val,
            "offsets": offsets,
        }

    @staticmethod
    def _metal_array(mtype: str, name: str, values) -> str:
        body = ", ".join(str(v) + ("f" if mtype == "float" else "") for v in values)
        return f"constant {mtype} {name}[] = {{{body}}};"

    # ------------------------------------------------------------------
    # Kernel
    # ------------------------------------------------------------------

    def emit_kernel(self, ir: TimberIR) -> str:
        if not ir.pipeline:
            raise ValueError("IR pipeline is empty")
        stage: TreeEnsembleStage = ir.pipeline[0]
        n_features = stage.n_features
        n_classes = max(stage.n_classes, 1)
        n_trees = len(stage.trees)
        base_score = stage.base_score

        flat = self._flatten_trees(stage)
        feat, thresh = flat["features"], flat["thresholds"]
        left, right = flat["left"], flat["right"]
        is_leaf, leaf_val, offsets = flat["is_leaf"], flat["leaf_values"], flat["offsets"]
        total_nodes = len(feat)

        lines = [
            "/* Auto-generated by TimberAccelerate — Metal backend */",
            "#include <metal_stdlib>",
            "using namespace metal;",
            "",
            f"#define N_TREES       {n_trees}",
            f"#define N_FEATURES    {n_features}",
            f"#define N_CLASSES     {n_classes}",
            f"#define TOTAL_NODES   {total_nodes}",
            f"#define BASE_SCORE    {base_score}f",
            "",
            "/* ---- Flat tree data in constant address space ---- */",
            self._metal_array("int", "tree_feature_idx", feat),
            self._metal_array("float", "tree_threshold", thresh),
            self._metal_array("int", "tree_left", left),
            self._metal_array("int", "tree_right", right),
            self._metal_array("int", "tree_is_leaf", is_leaf),
            self._metal_array("float", "tree_leaf_value", leaf_val),
            self._metal_array("int", "tree_offsets", offsets),
            "",
            "/* --------------------------------------------------",
            " * Compute kernel: one thread per sample.",
            " * -------------------------------------------------- */",
            "kernel void timber_infer(",
            "    device const float* input        [[buffer(0)]],",
            "    device       float* output       [[buffer(1)]],",
            "    device const int*   params       [[buffer(2)]],  /* [n_samples] */",
            "    uint gid [[thread_position_in_grid]])",
            "{",
            "    int n_samples = params[0];",
            "    if ((int)gid >= n_samples) return;",
            "",
            "    device const float* row = input + gid * N_FEATURES;",
            "",
        ]

        if n_classes <= 1:
            lines += [
                "    float acc = BASE_SCORE;",
                "",
                "    for (int t = 0; t < N_TREES; ++t) {",
                "        int idx = tree_offsets[t];",
                "        while (!tree_is_leaf[idx]) {",
                "            int fid = tree_feature_idx[idx];",
                "            idx = (row[fid] <= tree_threshold[idx])",
                "                  ? tree_left[idx] + tree_offsets[t]",
                "                  : tree_right[idx] + tree_offsets[t];",
                "        }",
                "        acc += tree_leaf_value[idx];",
                "    }",
                "",
                "    output[gid] = acc;",
            ]
        else:
            lines += [
                "    float acc[N_CLASSES];",
                "    for (int c = 0; c < N_CLASSES; ++c) acc[c] = BASE_SCORE;",
                "",
                "    for (int t = 0; t < N_TREES; ++t) {",
                "        int cls = t % N_CLASSES;",
                "        int idx = tree_offsets[t];",
                "        while (!tree_is_leaf[idx]) {",
                "            int fid = tree_feature_idx[idx];",
                "            idx = (row[fid] <= tree_threshold[idx])",
                "                  ? tree_left[idx] + tree_offsets[t]",
                "                  : tree_right[idx] + tree_offsets[t];",
                "        }",
                "        acc[cls] += tree_leaf_value[idx];",
                "    }",
                "",
                "    for (int c = 0; c < N_CLASSES; ++c)",
                "        output[gid * N_CLASSES + c] = acc[c];",
            ]

        lines += [
            "}",
            "",
        ]

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Host code (Objective-C compatible C using Metal framework)
    # ------------------------------------------------------------------

    def emit_host(self, ir: TimberIR) -> str:
        if not ir.pipeline:
            raise ValueError("IR pipeline is empty")
        stage = ir.pipeline[0]
        n_features = stage.n_features
        n_classes = max(stage.n_classes, 1)
        tpg = self.threads_per_group

        return "\n".join([
            "/* Auto-generated host driver — Metal backend */",
            '#include "model.h"',
            "#import <Foundation/Foundation.h>",
            "#import <Metal/Metal.h>",
            "#include <stdio.h>",
            "",
            f"#define N_FEATURES         {n_features}",
            f"#define N_CLASSES          {n_classes}",
            f"#define THREADS_PER_GROUP  {tpg}",
            "",
            "static id<MTLDevice>       _device   = nil;",
            "static id<MTLLibrary>      _library  = nil;",
            "static id<MTLComputePipelineState> _pipeline = nil;",
            "static id<MTLCommandQueue> _queue    = nil;",
            "",
            "static int _metal_init(void) {",
            "    if (_device) return 0;",
            "    _device = MTLCreateSystemDefaultDevice();",
            "    if (!_device) { fprintf(stderr, \"Metal: no GPU device found\\n\"); return -1; }",
            "",
            "    NSError* err = nil;",
            "    NSString* src = [NSString stringWithContentsOfFile:@\"kernel.metal\"",
            "                              encoding:NSUTF8StringEncoding error:&err];",
            "    if (!src) { fprintf(stderr, \"Metal: cannot read kernel.metal\\n\"); return -1; }",
            "",
            "    _library = [_device newLibraryWithSource:src options:nil error:&err];",
            "    if (!_library) { fprintf(stderr, \"Metal: compile error: %s\\n\",",
            "        [[err localizedDescription] UTF8String]); return -1; }",
            "",
            "    id<MTLFunction> fn = [_library newFunctionWithName:@\"timber_infer\"];",
            "    if (!fn) { fprintf(stderr, \"Metal: kernel not found\\n\"); return -1; }",
            "",
            "    _pipeline = [_device newComputePipelineStateWithFunction:fn error:&err];",
            "    _queue    = [_device newCommandQueue];",
            "    return 0;",
            "}",
            "",
            "int timber_predict_gpu(",
            "    const float* h_input,",
            "    float*       h_output,",
            "    int          n_samples)",
            "{",
            "    if (_metal_init() != 0) return -1;",
            "",
            "    size_t in_bytes  = (size_t)n_samples * N_FEATURES * sizeof(float);",
            "    size_t out_bytes = (size_t)n_samples * N_CLASSES  * sizeof(float);",
            "",
            "    id<MTLBuffer> buf_in  = [_device newBufferWithBytes:h_input",
            "                                      length:in_bytes",
            "                                      options:MTLResourceStorageModeShared];",
            "    id<MTLBuffer> buf_out = [_device newBufferWithLength:out_bytes",
            "                                      options:MTLResourceStorageModeShared];",
            "",
            "    int params[1] = { n_samples };",
            "    id<MTLBuffer> buf_params = [_device newBufferWithBytes:params",
            "                                         length:sizeof(params)",
            "                                         options:MTLResourceStorageModeShared];",
            "",
            "    id<MTLCommandBuffer> cmd = [_queue commandBuffer];",
            "    id<MTLComputeCommandEncoder> enc = [cmd computeCommandEncoder];",
            "",
            "    [enc setComputePipelineState:_pipeline];",
            "    [enc setBuffer:buf_in     offset:0 atIndex:0];",
            "    [enc setBuffer:buf_out    offset:0 atIndex:1];",
            "    [enc setBuffer:buf_params offset:0 atIndex:2];",
            "",
            "    MTLSize grid  = MTLSizeMake(n_samples, 1, 1);",
            "    MTLSize group = MTLSizeMake(THREADS_PER_GROUP, 1, 1);",
            "    [enc dispatchThreads:grid threadsPerThreadgroup:group];",
            "    [enc endEncoding];",
            "",
            "    [cmd commit];",
            "    [cmd waitUntilCompleted];",
            "",
            "    memcpy(h_output, [buf_out contents], out_bytes);",
            "    return 0;",
            "}",
            "",
        ])

    # ------------------------------------------------------------------
    # Build script
    # ------------------------------------------------------------------

    def emit_build_script(self, ir: TimberIR) -> str:
        if not ir.pipeline:
            raise ValueError("IR pipeline is empty")
        return "\n".join([
            "#!/bin/bash",
            "# Build script for Metal backend",
            "set -euo pipefail",
            "",
            "# Compile Metal shader to metallib",
            "xcrun -sdk macosx metal -c kernel.metal -o kernel.air",
            "xcrun -sdk macosx metallib kernel.air -o default.metallib",
            "",
            "# Compile host code",
            "clang -c -std=c11 -fobjc-arc host.c -o host.o",
            "clang -c -std=c11 model_data.c -o model_data.o",
            "",
            "# Link",
            "clang host.o model_data.o \\",
            "    -framework Metal -framework Foundation \\",
            "    -o timber_infer",
            "",
            'echo "Build complete: ./timber_infer"',
            "",
        ])
