"""OpenCL emitter — generates .cl kernels for cross-platform GPUs."""

from __future__ import annotations

from timber.accel.accel.gpu.base import GPUEmitterBase
from timber.codegen.c99 import TargetSpec
from timber.ir.model import TimberIR, TreeEnsembleStage


class OpenCLEmitter(GPUEmitterBase):
    """Emit OpenCL kernels with one work-item per sample inference."""

    def __init__(self, target: TargetSpec, gpu_config: dict):
        super().__init__(target, gpu_config)
        self.local_work_size = gpu_config.get("local_work_size", 256)

    def backend_name(self) -> str:
        return "opencl"

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _flatten_trees(ir_or_stage):
        """Flatten all trees in a stage into contiguous arrays.

        Accepts either a TimberIR (extracts first TreeEnsembleStage) or
        a TreeEnsembleStage directly.

        Returns dict with keys: features, thresholds, left, right, is_leaf,
        leaf_values, offsets.
        """
        if isinstance(ir_or_stage, TimberIR):
            stage = None
            for s in ir_or_stage.pipeline:
                if isinstance(s, TreeEnsembleStage):
                    stage = s
                    break
            if stage is None:
                raise ValueError("TimberIR contains no TreeEnsembleStage")
        else:
            stage = ir_or_stage
        feat, thresh, left, right, is_leaf, leaf_val = [], [], [], [], [], []
        offsets = []
        for tree in stage.trees:
            offsets.append(len(feat))
            for node in tree.nodes:
                feat.append(node.feature_index if not node.is_leaf else -1)
                thresh.append(node.threshold if not node.is_leaf else 0.0)
                left.append(node.left_child if not node.is_leaf else -1)
                right.append(node.right_child if not node.is_leaf else -1)
                is_leaf.append(1 if node.is_leaf else 0)
                leaf_val.append(node.leaf_value if node.is_leaf else 0.0)
        offsets.append(len(feat))
        return {
            "features": feat,
            "thresholds": thresh,
            "left": left,
            "right": right,
            "is_leaf": is_leaf,
            "leaf_values": leaf_val,
            "offsets": offsets,
        }

    @staticmethod
    def _cl_array(ctype: str, name: str, values) -> str:
        body = ", ".join(str(v) + ("f" if ctype == "float" else "") for v in values)
        return f"__constant {ctype} {name}[] = {{{body}}};"

    # ------------------------------------------------------------------
    # Kernel
    # ------------------------------------------------------------------

    def emit_kernel(self, ir: TimberIR) -> str:
        if not ir.pipeline:
            raise ValueError("IR pipeline is empty")
        stage: TreeEnsembleStage = ir.pipeline[0]
        n_features = stage.n_features
        n_classes = max(stage.n_classes, 1)
        n_trees = len(stage.trees)
        base_score = stage.base_score

        flat = self._flatten_trees(stage)
        feat, thresh = flat["features"], flat["thresholds"]
        left, right = flat["left"], flat["right"]
        is_leaf, leaf_val, offsets = flat["is_leaf"], flat["leaf_values"], flat["offsets"]

        lines = [
            "/* Auto-generated by TimberAccelerate — OpenCL backend */",
            "",
            f"#define N_TREES       {n_trees}",
            f"#define N_FEATURES    {n_features}",
            f"#define N_CLASSES     {n_classes}",
            f"#define TOTAL_NODES   {len(feat)}",
            f"#define BASE_SCORE    {base_score}f",
            "",
            "/* ---- Flat tree data in __constant memory ---- */",
            self._cl_array("int", "tree_feature_idx", feat),
            self._cl_array("float", "tree_threshold", thresh),
            self._cl_array("int", "tree_left", left),
            self._cl_array("int", "tree_right", right),
            self._cl_array("int", "tree_is_leaf", is_leaf),
            self._cl_array("float", "tree_leaf_value", leaf_val),
            self._cl_array("int", "tree_offsets", offsets),
            "",
            "/* --------------------------------------------------",
            " * Kernel: one work-item per sample.",
            " * -------------------------------------------------- */",
            "__kernel void timber_infer(",
            "    __global const float* input,   /* [n_samples, N_FEATURES] */",
            "    __global       float* output,  /* [n_samples, N_CLASSES]  */",
            "    int n_samples)",
            "{",
            "    int gid = get_global_id(0);",
            "    if (gid >= n_samples) return;",
            "",
            "    __global const float* row = input + gid * N_FEATURES;",
            "",
        ]

        if n_classes <= 1:
            lines += [
                "    float acc = BASE_SCORE;",
                "",
                "    for (int t = 0; t < N_TREES; ++t) {",
                "        int idx = tree_offsets[t];",
                "        while (!tree_is_leaf[idx]) {",
                "            int fid = tree_feature_idx[idx];",
                "            idx = (row[fid] <= tree_threshold[idx])",
                "                  ? tree_left[idx] + tree_offsets[t]",
                "                  : tree_right[idx] + tree_offsets[t];",
                "        }",
                "        acc += tree_leaf_value[idx];",
                "    }",
                "",
                "    output[gid] = acc;",
            ]
        else:
            lines += [
                "    float acc[N_CLASSES];",
                "    for (int c = 0; c < N_CLASSES; ++c) acc[c] = BASE_SCORE;",
                "",
                "    for (int t = 0; t < N_TREES; ++t) {",
                "        int cls = t % N_CLASSES;",
                "        int idx = tree_offsets[t];",
                "        while (!tree_is_leaf[idx]) {",
                "            int fid = tree_feature_idx[idx];",
                "            idx = (row[fid] <= tree_threshold[idx])",
                "                  ? tree_left[idx] + tree_offsets[t]",
                "                  : tree_right[idx] + tree_offsets[t];",
                "        }",
                "        acc[cls] += tree_leaf_value[idx];",
                "    }",
                "",
                "    for (int c = 0; c < N_CLASSES; ++c)",
                "        output[gid * N_CLASSES + c] = acc[c];",
            ]

        lines += [
            "}",
            "",
        ]

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Host code
    # ------------------------------------------------------------------

    def emit_host(self, ir: TimberIR) -> str:
        if not ir.pipeline:
            raise ValueError("IR pipeline is empty")
        stage = ir.pipeline[0]
        n_features = stage.n_features
        n_classes = max(stage.n_classes, 1)
        lws = self.local_work_size

        return "\n".join([
            "/* Auto-generated host driver — OpenCL backend */",
            '#include "model.h"',
            "",
            "#ifdef __APPLE__",
            "#include <OpenCL/opencl.h>",
            "#else",
            "#include <CL/cl.h>",
            "#endif",
            "",
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "#include <string.h>",
            "",
            f"#define N_FEATURES       {n_features}",
            f"#define N_CLASSES        {n_classes}",
            f"#define LOCAL_WORK_SIZE  {lws}",
            "",
            "/* Read kernel source from file at runtime. */",
            "static char* _read_file(const char* path, size_t* out_len) {",
            '    FILE* f = fopen(path, "rb");',
            "    if (!f) return NULL;",
            "    fseek(f, 0, SEEK_END);",
            "    size_t len = (size_t)ftell(f);",
            "    fseek(f, 0, SEEK_SET);",
            "    char* buf = (char*)malloc(len + 1);",
            "    fread(buf, 1, len, f);",
            "    buf[len] = '\\0';",
            "    fclose(f);",
            "    if (out_len) *out_len = len;",
            "    return buf;",
            "}",
            "",
            "static cl_context       _ctx      = NULL;",
            "static cl_command_queue  _queue    = NULL;",
            "static cl_program       _program  = NULL;",
            "static cl_kernel        _kernel   = NULL;",
            "",
            "static int _ocl_init(void) {",
            "    if (_ctx) return 0;",
            "",
            "    cl_int err;",
            "    cl_platform_id platform;",
            "    cl_device_id   device;",
            "",
            "    err = clGetPlatformIDs(1, &platform, NULL);",
            '    if (err != CL_SUCCESS) { fprintf(stderr, "OpenCL: no platform\\n"); return -1; }',
            "",
            "    err = clGetDeviceIDs(platform, CL_DEVICE_TYPE_GPU, 1, &device, NULL);",
            "    if (err != CL_SUCCESS) {",
            "        /* Fallback to any available device */",
            "        err = clGetDeviceIDs(platform, CL_DEVICE_TYPE_ALL, 1, &device, NULL);",
            '        if (err != CL_SUCCESS) { fprintf(stderr, "OpenCL: no device\\n"); return -1; }',
            "    }",
            "",
            "    _ctx = clCreateContext(NULL, 1, &device, NULL, NULL, &err);",
            '    if (err != CL_SUCCESS) { fprintf(stderr, "OpenCL: context error\\n"); return -1; }',
            "",
            "    _queue = clCreateCommandQueue(_ctx, device, 0, &err);",
            "",
            "    size_t src_len = 0;",
            '    char* src = _read_file("kernel.cl", &src_len);',
            '    if (!src) { fprintf(stderr, "OpenCL: cannot read kernel.cl\\n"); return -1; }',
            "",
            "    _program = clCreateProgramWithSource(_ctx, 1, (const char**)&src, &src_len, &err);",
            "    free(src);",
            "",
            '    err = clBuildProgram(_program, 1, &device, "-cl-fast-relaxed-math", NULL, NULL);',
            "    if (err != CL_SUCCESS) {",
            "        size_t log_len;",
            "        clGetProgramBuildInfo(_program, device, CL_PROGRAM_BUILD_LOG, 0, NULL, &log_len);",
            "        char* log = (char*)malloc(log_len);",
            "        clGetProgramBuildInfo(_program, device, CL_PROGRAM_BUILD_LOG, log_len, log, NULL);",
            '        fprintf(stderr, "OpenCL build log:\\n%s\\n", log);',
            "        free(log);",
            "        return -1;",
            "    }",
            "",
            '    _kernel = clCreateKernel(_program, "timber_infer", &err);',
            '    if (err != CL_SUCCESS) { fprintf(stderr, "OpenCL: kernel not found\\n"); return -1; }',
            "",
            "    return 0;",
            "}",
            "",
            "int timber_predict_gpu(",
            "    const float* h_input,",
            "    float*       h_output,",
            "    int          n_samples)",
            "{",
            "    if (_ocl_init() != 0) return -1;",
            "",
            "    cl_int err;",
            "    size_t in_bytes  = (size_t)n_samples * N_FEATURES * sizeof(float);",
            "    size_t out_bytes = (size_t)n_samples * N_CLASSES  * sizeof(float);",
            "",
            "    cl_mem d_input  = clCreateBuffer(_ctx, CL_MEM_READ_ONLY  | CL_MEM_COPY_HOST_PTR,",
            "                                     in_bytes, (void*)h_input, &err);",
            "    cl_mem d_output = clCreateBuffer(_ctx, CL_MEM_WRITE_ONLY,",
            "                                     out_bytes, NULL, &err);",
            "",
            "    clSetKernelArg(_kernel, 0, sizeof(cl_mem), &d_input);",
            "    clSetKernelArg(_kernel, 1, sizeof(cl_mem), &d_output);",
            "    clSetKernelArg(_kernel, 2, sizeof(int),    &n_samples);",
            "",
            "    /* Round global size up to multiple of local work size */",
            "    size_t local  = LOCAL_WORK_SIZE;",
            "    size_t global = ((n_samples + local - 1) / local) * local;",
            "",
            "    err = clEnqueueNDRangeKernel(_queue, _kernel, 1, NULL,",
            "                                 &global, &local, 0, NULL, NULL);",
            '    if (err != CL_SUCCESS) { fprintf(stderr, "OpenCL: enqueue error %d\\n", err); }',
            "",
            "    clEnqueueReadBuffer(_queue, d_output, CL_TRUE, 0,",
            "                        out_bytes, h_output, 0, NULL, NULL);",
            "",
            "    clReleaseMemObject(d_input);",
            "    clReleaseMemObject(d_output);",
            "    return 0;",
            "}",
            "",
            "void timber_ocl_cleanup(void) {",
            "    if (_kernel)  clReleaseKernel(_kernel);",
            "    if (_program) clReleaseProgram(_program);",
            "    if (_queue)   clReleaseCommandQueue(_queue);",
            "    if (_ctx)     clReleaseContext(_ctx);",
            "    _kernel = NULL; _program = NULL; _queue = NULL; _ctx = NULL;",
            "}",
            "",
        ])

    # ------------------------------------------------------------------
    # Build script
    # ------------------------------------------------------------------

    def emit_build_script(self, ir: TimberIR) -> str:
        if not ir.pipeline:
            raise ValueError("IR pipeline is empty")
        return "\n".join([
            "cmake_minimum_required(VERSION 3.12)",
            "project(timber_opencl LANGUAGES C)",
            "",
            "set(CMAKE_C_STANDARD 11)",
            "",
            "find_package(OpenCL REQUIRED)",
            "",
            "add_library(timber_model STATIC",
            "    host.c",
            "    model_data.c",
            ")",
            "",
            "target_include_directories(timber_model PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})",
            "target_link_libraries(timber_model PUBLIC OpenCL::OpenCL)",
            "",
            "# Install the .cl kernel source alongside the binary",
            "configure_file(kernel.cl ${CMAKE_BINARY_DIR}/kernel.cl COPYONLY)",
            "",
            "# Optional: build a standalone benchmark executable",
            "# add_executable(timber_bench bench.c)",
            "# target_link_libraries(timber_bench PRIVATE timber_model)",
            "",
        ])
